### PR TITLE
2614/Add protocol option to email template context

### LINKED ISSUE #2614: [Templates] Logo URL is broken in mail body when remove account
### What I'm trying to achieve
Logo broken in mail body when remove account

### Steps to reproduce the problem
1. login
2. enter to account page
3. click "remove account"
4. see broken logo url, must be like http://localhost/static/images/logo-document.svg , but got http://127.0.0.1/en/products/mccarthy-llc-2/%3C%3C%20MISSING%20VARIABLE%20%22protocol%22%20%3E%3E://localhost:80/static/images/logo-document.svg . In another mail (in my case order details logo show normal).

### Screenshots
7b790d456a 1

To read mail use: https://github.com/mirumee/saleor/issues/2610

### PR DESCRIPTION
**Pull request by tomcio1205**
I want to merge this change because it resolves #2614

### CODE REVIEW

**Comment by Pacu2** [comment]
Thanks! Your changes indeed solve the problem, therefore I think we should not glue the URL on the templates(which leads to the bugs like this one), instead, we should pass the full absolute URL as the context variable, from the view to the template

**Comment by Pacu2** [comment]
I've created an issue for fixing the URL creation in email's templates #2730

**Comment by tomcio1205** [comment]
@Pacu2 so I must change all templates which are uses the header.mjml shared file. Should I do this on this branch ?

**Comment by tomcio1205** [comment]
@Pacu2  I think it could be close now, because pr #2734 also resolve this issue

**Pull request closed without merging**
