### PR TITLE
Raise an error for an empty key in metadata

### PR DESCRIPTION
**Pull request by IKarbowiak**
Raise an error when an empty key for metadata is provided.

[SALEOR-983](https://app.clickup.com/t/2549495/SALEOR-983)

# Impact

* [ ] New migrations
* [x] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [x] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [x] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-983 Empty keys in metadata should be invalid](https://app.clickup.com/t/2549495/SALEOR-983)

**Review by maarcingebala — APPROVED** [review]
This is fine but I'm thinking if we should rename the error code to `REQUIRED` which means the same and is more consistent with other error codes. But maybe there is no need. @dominik-zeglen do you have any preference here?

**Comment by dominik-zeglen** [comment]
`REQUIRED` is way better, consistent with the rest of the code :)

**Review by fowczarek — CHANGES_REQUESTED** [review]
We should also add this validation to `UpdatePrivateMetadata`.

**Review by fowczarek — APPROVED** [review]

**Review by maarcingebala — APPROVED** [review]

**Pull request merged**
