### PR TITLE
Remove --dev from pipenv install

### PR DESCRIPTION
**Pull request by stephenmoloney**
What does this PR do?

  - removes the flag `--dev` from `pipenv install`

Why is this PR needed?

  - the resultant docker image should not include dev deps

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] GraphQL schema and type definitions are up to date.

### CODE REVIEW

**Comment by stephenmoloney** [comment]
`silk` and `django-debug-toolbar` already seem to be part of default deps - i couldn't find them in the dev deps.

**Comment by stephenmoloney** [comment]
I'm seeing errors at the moment but I haven't run saleor on docker for a long time, it could be something else causing it.

example:
```
web_1     | FileNotFoundError: [Errno 2] No such file or directory: '/app/media/products/saleor/static/placeholders/candy/1.jpg'
web_1     | ERROR saleor.product.templatetags.product_images Thumbnail fetch failed [PID:12:Thread-49]
web_1     | Traceback (most recent call last):
web_1     |   File "/app/saleor/product/templatetags/product_images.py", line 87, in get_thumbnail
web_1     |     thumbnail = getattr(instance, method)[used_size]
web_1     |   File "/usr/local/lib/python3.6/site-packages/versatileimagefield/datastructures/sizedimage.py", line 149, in __getitem__
web_1     |     height=height
web_1     |   File "/usr/local/lib/python3.6/site-packages/versatileimagefield/datastructures/sizedimage.py", line 201, in create_resized_image
web_1     |     path_to_image
web_1     |   File "/usr/local/lib/python3.6/site-packages/versatileimagefield/datastructures/base.py", line 140, in retrieve_image
web_1     |     image = self.storage.open(path_to_image, 'rb')
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 33, in open
web_1     |     return self._open(name, mode)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 218, in _open
web_1     |     return File(open(self.path(name), mode))
```

**Comment by stephenmoloney** [comment]
Ok, for more information purposes, I checked out master and ran 

```
docker-compose build --no-cache && docker-compose down --volumes --remove-orphans && docker-compose run --rm web bash -c 'python3 manage.py migrate' && docker-compose run --rm web bash -c 'python3 manage.py collectstatic --noinput' && sleep 40s && docker-compose run --rm web bash -c 'python3 manage.py populatedb --createsuperuser' && docker-compose up -d
```

but seeing similar errors:

```
web_1     | FileNotFoundError: [Errno 2] No such file or directory: '/app/media/products/saleor/static/placeholders/t-shirts/6_nIkZUF6.jpg'
web_1     | ERROR saleor.product.templatetags.product_images Thumbnail fetch failed [PID:10:Thread-43]
web_1     | Traceback (most recent call last):
web_1     |   File "/app/saleor/product/templatetags/product_images.py", line 87, in get_thumbnail
web_1     |     thumbnail = getattr(instance, method)[used_size]
web_1     |   File "/usr/local/lib/python3.6/site-packages/versatileimagefield/datastructures/sizedimage.py", line 149, in __getitem__
web_1     |     height=height
web_1     |   File "/usr/local/lib/python3.6/site-packages/versatileimagefield/datastructures/sizedimage.py", line 201, in create_resized_image
web_1     |     path_to_image
web_1     |   File "/usr/local/lib/python3.6/site-packages/versatileimagefield/datastructures/base.py", line 140, in retrieve_image
web_1     |     image = self.storage.open(path_to_image, 'rb')
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 33, in open
web_1     |     return self._open(name, mode)
web_1     |   File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 218, in _open
web_1     |     return File(open(self.path(name), mode))
```

Seems like something with the versatileimage manager not seeing the images.

The `/app/media` directory seems to be emtpy too.

```
u2@u2-desktop:~/Documents/repos/opensource/saleor$ docker-compose exec web ls -al /app/media
total 12
drwxr-xr-x 2 saleor saleor 4096 Oct 15 21:24 .
drwxr-xr-x 1 saleor saleor 4096 Oct 15 21:24 ..
```

So this seems to be an issue on master - nobody else has noticed it ?

**Comment by jxltom** [comment]
Removing ```--dev``` will break the tests in circle CI

https://github.com/mirumee/saleor/blob/7f954d9b879f1b0dbbb74a20bb0608f01a55c762/.circleci/config.yml#L31

**Comment by stephenmoloney** [comment]
@jxltom 
Can you add some information why? any errors, etc. We are trying to ascertain what dependencies need to be moved into default deps.

**Comment by jxltom** [comment]
The ```pytest``` is running insider the built docker image, so obviously pytest and all its plugins are needed. Otherwise ```pytest``` command can not be found at all.

- You can move all test packages to default packages but I won't recommend that since test packages has nothing to do with saleor's core codebase and they shouldn't be installed in production server.

- Or you can add ```--dev``` to ```pipenv install``` when building docker just like now.

- Or you can remove unittest in circle CI.

- Or you can update the circle CI's workflow which contains two job, one job should build a docker image with dev packages and run the unittest. The other should build docker image with only default packages and then push to saleor's docker registry which then can be used in production server.

IMHO, the third solution is the easiest one but the fouth is the best one though it requires some time to do that.

**Comment by stephenmoloney** [comment]
closing in favour of #3118

**Pull request closed without merging**
