### PR TITLE
Use Watchman for autoreload

### PR DESCRIPTION
**Pull request by vladox**
I want to merge this change because...

Resolves: #4409

### Screenshots

Before: 

Activity_Monitor__All_Processes_

1__vladox_Vladimirs-MBP____Dev_Python_Github_saleor__zsh_

After:

Activity_Monitor__All_Processes__and_T-shirt_-_Saleor_e-commerce

1__docker-compose_up__docker-compose_

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] Database migration files are up to date.
1. [x] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] GraphQL schema and type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by vladox** [comment]
Not really sure if you want the Pipfile.lock file to be updated to the latest versions, according to the Pipfile is like that but please have a look and let me know

**Comment by vladox** [comment]
Also, feel free to reference you own Docker image for Watchman, it's done like that to avoid the compilations time required of Watchman on each installation.

**Comment by vladox** [comment]
@NyanKiyoshi That could be an option but this is probably also an issue in other platforms not only restricted to docker. It's the way Django detects changes in the code base and Watchman seems to be the preferred and more efficient solution.

**Comment by django-queries** [comment]
Here is the report for cd10804ccaf1834781a28ec46f53ed348dc2f5dd (elpatiostudio/saleor @ fix/docker-high-cpu-usage)
Base comparison is 5e4e4a4259a011d24b04ebd24c77c689de843fa1.



<details><summary>No differences were found. (click me)</summary>
<p>

```diff
# api.benchmark checkout
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  add billing address to checkout     	         38	         38	             20
  add shipping to checkout            	          7	          7	              0
  checkout payment charge             	         14	         14	              0
  complete checkout                   	          6	          6	              0
  create checkout                     	         52	         52	             24

# api.benchmark homepage
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  retrieve main menu                  	          5	          5	              0
  retrieve product list               	          4	          4	              0
  retrieve secondary menu             	          5	          5	              0
  retrieve shop                       	          2	          2	              0

# api.benchmark product
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  product details                     	         15	         15	              3

# api.benchmark variant
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  retrieve variant list               	         18	         18	              8
```

</p>
</details>

**Comment by vladox** [comment]
> I would think you could simply add `pip install pywatchman` in the dockerfile so it doesn't affect non-docker users?

@NyanKiyoshi  I tried a non dockerized install and this doesn't affect it.  

@patrys @maarcingebala do you think you can review this, it really makes a difference for dockerized installs on Mac and Linux. I'll prefer to work on with your repo and not to be forced to work on a fork. Thanks :)

**Comment by maarcingebala** [comment]
@vladox Hey, we've just migrated to Poetry (#3894 🎉 ) which means this PR needs to be updated if we want to merge it.

**Comment by vladox** [comment]
@maarcingebala @NyanKiyoshi I'll be having a look today and updating the status, thanks for the feedback!

**Comment by NyanKiyoshi** [comment]
Would be nice to have 👍 Whenever you have a few minutes to take a look 😄

**Comment by vladox** [comment]
> Would be nice to have  Whenever you have a few minutes to take a look

Sorry for the lack of activity on this, now that the work load is decreasing in these coming days I'll submit all pending changes.
Thanks for the message

**Pull request closed without merging**
