### PR TITLE
Solve an auto-resize conflict between Materialize and medium-editor

### PR DESCRIPTION
**Pull request by adonig**
I want to merge this change because it fixes an auto-resize conflict between Materialize and medium-editor.

### Screenshots

- [before](https://imgur.com/a/dldMqPk)
- [after](https://imgur.com/a/0m9zVCo)

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] GraphQL schema and type definitions are up to date.

### CODE REVIEW

**Comment by maarcingebala** [comment]
Thanks for the PR @adonig! I see that Python tests are failing. Could you edit this PR and leave only JS changes so we can fix the editor first? Python changes could be submitted in a separate PR with proper tests.

**Comment by adonig** [comment]
> Thanks for the PR @adonig! I see that Python tests are failing. Could you edit this PR and leave only JS changes so we can fix the editor first? Python changes could be submitted in a separate PR with proper tests.

Ups. I didn't want to add the second commit to this pull request. It was a change I added to my personal fork after I filed the pull request. I think I probably should use more branches. My GitHub fu isn't that great. How can I remove a commit from a pull request? :-)

**Comment by NyanKiyoshi** [comment]
@adonig you could rewrite the history (copy paste carefully, those commands can be dangerous).

```
git reset HEAD~1 --soft    # Remove the latest commit from the branch
git stash                  # Add the latest commit changes to the stash
git push -f                # Force-push the new commit history

git checkout -b myfilters  # Create a new branch for the changes that were stashed
git stash pop              # Retrieve the changes from the stash
```

**Comment by adonig** [comment]
> @adonig you could rewrite the history (copy paste carefully, those commands can be dangerous).

Thank you. It looks like it worked. I guess I have to read a book about git one day :-)

**Comment by maarcingebala** [comment]
Congratulations on your first PR to Saleor! 🎉

**Pull request merged**
