### PR TITLE
Email plugin does not choose proper channel configuration

### PR DESCRIPTION
**Pull request by krzysztofwolski**
Ref #7876

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-4227 Email plugin does not choose proper channel configuration](https://app.clickup.com/t/2549495/SALEOR-4227)

**Comment by maarcingebala** [comment]
@krzysztofwolski Linters are failing here and we should open the PR to `master` when targeting 3.1.

**Comment by maarcingebala** [comment]
@krzysztofwolski This should be rebased against `master`.

**Comment by maarcingebala** [comment]
Closing in favor of https://github.com/mirumee/saleor/pull/7890

**Pull request closed without merging**
