### PR TITLE
Build a docker image with dev dependencies as optional

### PR DESCRIPTION
**Pull request by stephenmoloney**
What does this commit/MR/PR do?

- Build a docker image with dev dependencies as optional

Why is this commit/MR/PR needed?

- Avoid forcing the inclusion of dev dependencies

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] GraphQL schema and type definitions are up to date.

### CODE REVIEW

**Comment by ajostergaard** [comment]
@stephenmoloney any chance of documenting this new feature?

**Comment by stephenmoloney** [comment]
@ajostergaard 

If this PR is accepted, I will add documentation, sure. 

I'm not sure either this is the best approach.

The alternative is to create a separate `Dockerfile.prod` for production images without `pipenv`

Relates to https://github.com/mirumee/saleor/issues/3110

I do think there should be a production ready - production only docker image though.

**Comment by patrys** [comment]
I think the only reason we've added `--dev` was because `silk` and `django-debug-toolbar` were placed in the wrong section of the `Pipfile`. We do not need to install dev tools inside the Docker container so the non-production mode is not really needed, we should instead make sure that all actual dependencies are in the default dependencies section and not in the dev dependencies section.

**Comment by stephenmoloney** [comment]
ok, so if i add `silk and django-debug-toolbar` to the default deps and remove `--dev`, is that sufficient ?

I can close this PR and open a new one with those changes.

**Comment by patrys** [comment]
@stephenmoloney Yes, move those (and any other conditionally enabled deps if you find any) and remove `--dev` from the install command in Dockerfile.

**Comment by stephenmoloney** [comment]
Ref #3117

**Pull request closed without merging**
