### PR TITLE
FIx delivery group deletion on order line removal.

### PR DESCRIPTION
**Pull request by itbabu**
Hello,

Steps to reproduce the issue
- Dashboard
- Go to an order details page with more than one line.
- Delete a line

The delivery group is removed even if there are other lines.

I added few tests for this view following #473 directions.

Side note.. a cancelled order without delivery groups doesn't look cancelled.
The only visual reference is the second line in the card to the right 
schermata del 2017-02-25 14-01-29

### CODE REVIEW

**Comment by patrys** [comment]
This is already fixed by the dashboard revamp PR and should land early next week. Thank you for reporting.

**Comment by patrys** [comment]
I'll keep this open to try and merge your test cases once #920 lands.

**Comment by itbabu** [comment]
Ok,
I've just rebased this after keeping only tests and one view change.

**Comment by patrys** [comment]
Travis says that build failed but won't show me the actual results 😭

**Comment by itbabu** [comment]
should be fixed now:
 ```from django.urls import reverse``` works only from Django 1.10

**Pull request merged**
