### PR TITLE
Fix subcategory update redirection

### LINKED ISSUE #4798: Dashboard Updating subcategories redirecting to the wrong page
### What I'm trying to achieve
Updating a subcategory needs to redirect to the Category page when done

### Steps to reproduce the problem
1.  Lets say I start on the Category Grocery page (http://localhost:8000/dashboard/categories/8/) and add a subcategory "grocery" and save it
2. Go update the subcategory you just created and click inside to update it this will redirect you to something like a page like: http://localhost:8000/dashboard/categories/23/ This is a page of the subcategory with a subcategory section you can add. What it should be redirect you back to the Category Grocery page to add additional groceries.

### What I expected to happen
1. Redirect to the categories page when finish updating. (Guessing issue is with how the view is written)
2. For the subcategories page you should not be able to add more subcategories 

### Screenshot

Untitled1

**System information**
Operating system: Windows
Browser: Firefox
Saleor v 2.8

### PR DESCRIPTION
**Pull request by iflare3g**
I want to merge this change because it fixes #4798 
With this fix, form into subcategory page is been removed and subcategory's update redirects to the parent category page.

### Screenshots

**BEFORE**
66124019-30eae180-e598-11e9-92ae-a522974c4fda

**AFTER**
Schermata 2019-10-07 alle 11 02 42

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] Database migration files are up to date.
1. [x] The changes are tested.
1. [ ] GraphQL schema and type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by django-queries** [comment]
Here is the report for dc101968b619579013356eea4ab32c59a2fd777c (iflare3g/saleor @ feature/fix-category-update-redirect)
Base comparison is 6f80633a5e9d88675fb78d1a22d1d763dfe6aeae.



<details><summary>No differences were found. (click me)</summary>
<p>

```diff
# api.benchmark checkout
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  add billing address to checkout            	         34	         34	             20
  add shipping to checkout                   	          7	          7	              0
  checkout payment charge                    	         14	         14	              0
  complete checkout                          	          6	          6	              0
  create checkout                            	         48	         48	             24

# api.benchmark homepage
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  retrieve main menu                         	          5	          5	              0
  retrieve product list                      	          4	          4	              0
  retrieve secondary menu                    	          5	          5	              0
  retrieve shop                              	          2	          2	              0

# api.benchmark product
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  product details                            	         15	         15	              3
  retrieve product attributes                	         13	         13	              2

# api.benchmark variant
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  retrieve variant list                      	         18	         18	              8

# api product sorting attributes
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  sort product not having attribute data     	         21	         21	              0
```

</p>
</details>

**Comment by maarcingebala** [comment]
Hey, thanks for opening the PR. Sorry for not giving any input earlier, but I think it's expected to have the "sub-categories" form when you're already viewing a subcategory. Categories are based on a tree structure and can be nested. You should be able to create structures like:
- Apparel
  - T-shirts
    - Basic
    - Polo

This is a general idea of how categories work and I think it should stay like that.

**Comment by maarcingebala** [comment]
Maybe I misunderstood the issue, but if we kept the form on a subcategory page, then staying on that page after editing it also makes sense, because you may want to keep editing this page.

**Comment by iflare3g** [comment]
No worries.
So that issue isn't a valid one , right ? So this "fix" is not useful.

**Comment by maarcingebala** [comment]
I can imagine the behavior you suggested in the issue would be correct in some use-cases. If this is valid in your case than you should customize Saleor to use it. But in general terms, I think the behavior we have now is reasonable. I should have written that in the issue - sorry for the confusion.

**Comment by maarcingebala** [comment]
@iflare3g I'll close the PR and the issue, but we really appreciate your effort and would like to send you the gift anyway for participating in Hacktoberfest. Send me your shipping address to `marcin@mirumee.com` and we'll send you a small package 🙂.

**Comment by iflare3g** [comment]
No worries and thanks for the gift! 
I'll try to contribute to other relevant issues!

**Pull request closed without merging**
