### PR TITLE
Added translation fields in new static category template

### PR DESCRIPTION
**Pull request by julienfabre**
Some fields in the now static category page were not translatable. I added a `trans ` tag to them.

### CODE REVIEW

**Comment by elwoodxblues** [comment]
Thanks for the contribution @julienfabre! Since there are two commits that were later reverted, could you remove them and keep only the last one? You should be able to do this with `git rebase -i`. We're just updating translations and could use your PR.

**Comment by julienfabre** [comment]
My bad, commit history should be clean now

**Comment by julienfabre** [comment]
Would you mind re-building the corresponding .po files so that translation can be done on Transifex?

**Comment by elwoodxblues** [comment]
@koradon Already did it in PR #1181, including your changes.

**Pull request merged**
