### PR TITLE
Fix dashboard modal buttons

### PR DESCRIPTION
**Pull request by Satloff**

### CODE REVIEW

**Comment by Pacu2** [comment]
Hi @Satloff, thanks for the contribution! 
Could you provide brief description what you've fixed in this PR, or preferably some before/after screenshots, if changing the UI?

**Comment by Pacu2** [comment]
The difference is in hover state. 
hover_state
Blue one after changes provided by @Satloff, the right one is current state.
It's related to Dashboard inconsistences  #1310, as in most of the places we are using `blue` hover version.

**Comment by elwoodxblues** [comment]
I think what this PR does is changing hover state of buttons in modals in the first place. In our modals we have flat buttons that don't change the background color on hover, which is consistent with what MaterializeCSS documentation says. But all of the other buttons (not in modals) do change the background on hover. I'm not sure what is correct, but I think we once have a discussion about it and this difference is intentional.

The screenshot that @Pacu2 posted shows a different problem - in our stylesheets we still have `teal` color hardcoded, which used to be the secondary color. @dominik-zeglen Could you take care of that in your current PR?

**Comment by patrys** [comment]
Are we sure that borderless buttons should change their background color on hover? I think this does not happen often in material design applications.

**Comment by Satloff** [comment]
My mistake for not providing screenshots. My intention was to continue the standard styling used throughout the rest of the dashboard with respect to action buttons. Currently, there is no effect on button hover in select modals, which makes the user flow confusing. 

Without the change, with mouse over:
screen shot 2017-11-16 at 9 43 00 am

With the change, with mouse over:
screen shot 2017-11-16 at 9 40 37 am

**Comment by patrys** [comment]
I think the standard is (all that apply):
* for raised buttons raise the Z offset (layer height)
* for bordered buttons change background color
* for borderless buttons change text color

**Comment by Satloff** [comment]
Shouldn't table buttons (borderless flat) also apply to this standard? This seems to go against 80c03cb

**Comment by patrys** [comment]
@Satloff Yes, I believe they should.

**Pull request closed without merging**
