### PR TITLE
GraphQL API authentication

### LINKED ISSUE #1711: Enable JWT authorization in GraphQL API
We'll need a way to authorize access to specific endpoints in our API. There is a project that integrates [JWT](https://jwt.io/) with Graphene, I think it's worth checking out: https://github.com/flavors/django-graphql-jwt.

I was also wondering how will we handle separation between storefront and dashboard in the API. Most of the storefront's API will be public (except for stuff related to user account), while dashboard API will always require some authorization, so it might be convenient to have separate endpoints.

### PR DESCRIPTION
**Pull request by elwoodxblues**
This PR adds token-based authentication mechanism to our GraphQL API. I've used two packages:
- [django-graphql-jwt](https://github.com/flavors/django-graphql-jwt) - provides authentication mutations
- [django-graphql-extensions](https://github.com/flavors/django-graphql-extensions) - provides authentication decorators that can be used to restrict access to resolvers and mutations

Fixes #1711 

Authentication mutation were added to the storefront's API for now, but I'm wondering if they shouldn't be available in both APIs.

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] Python code quality checks pass: `pycodestyle`, `pydocstyle`, `pylint`.
1. [ ] JavaScript code quality checks pass: `eslint`.

### CODE REVIEW

**Comment by patrys** [comment]
Note: it seems `JWT_VERIFY_EXPIRATION` defaults to `False`.

**Comment by elwoodxblues** [comment]
@patrys We can enable it. What expiration time should we set?

**Comment by patrys** [comment]
I don't have a strong preference but I feel that issuing irrevocable credentials is asking for trouble. Invalidating JWT tokens is not trivial:
* simple expiration is the easiest
* blacklisting particular tokens is possible but not trivial (you likely don't keep a list of all issued tokens, the most practical approach would be to filter based on user ID and expiry date but that relies on the expiration date being set)
* rotating secrets would invalidate all tokens in existence but will affect unrelated mechanisms relying on the SECRET_KEY (invalidating things like password reset links, signed cookies etc.)

**Comment by elwoodxblues** [comment]
@patrys For now, I'd go with the simplest approach. However, I'm not sure what time delta is adequate here. The default 5 minutes seems very short, but that's the default also in PyJWT that is used underneath. Also, what do you think about exposing those mutations only in the storefront's API? I'm wondering if it should stay only there or be duplicated in both APIs.

**Comment by patrys** [comment]
Exposing them in one endpoint but not another will complicate the client design as the implementation would require two separate Apollo/Relay clients (and in most cases both schemas).

**Comment by elwoodxblues** [comment]
I've tested `JWT_VERIFY_EXPIRATION` and it works as expected with the default settings which I believe are proper - token has to be refreshed every 5 minutes, but it expires anyway after 7 days from the first authentication. `JWT_VERIFY_EXPIRATION` is set as env variable.

**Comment by patrys** [comment]
Related changes for the client: https://blog.beeaweso.me/refreshing-token-based-authentication-with-apollo-client-2-0-7d45c20dc703

**Pull request merged**
