### PR TITLE
Use dropdown menu for country area choices

### PR DESCRIPTION
**Pull request by primal100**
I want to merge this change because...

It provides a fix for issue #1335 and improves usability.
In the CountryAwareAddressForm, currently country area (states, counties, provinces, etc) is a regular input field for all countries. Validation will fail if the user doesn't type one of the listed country area values exactly, if that country has country area choices.  Expecting endusers to enter country area values exactly (especially for Irish counties where it is necessary to enter Co. before the county name) is inconvenient. So it makes sense to provide the choices as a dropdown field, but only for countries that have country area choices. The others will still use a regular input field.

Here's examples for US and Ireland after the change:

capture_usa
capture_ireland

Here's an example for Colombia, which does not have country area choices and thus, still uses an input field:

capture_colombia

### Pull Request Checklist

(Please keep this section. It will make maintainer's life easier.)

1. [x] Privileged views and APIs are guarded by proper permission checks.
1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Database queries are optimized and the number of queries is constant.
1. [x] The changes are tested.
1. [x] The code is documented (docstrings, project documentation).
1. [x] Python code quality checks pass: `pycodestyle`, `pydocstyle`, `pylint`.
1. [x] JavaScript code quality checks pass: `eslint`.

### CODE REVIEW

**Comment by patrys** [comment]
I like this but for autocomplete-related reasons would prefer to use an input with a datalist where possible. For example when auto-completing an address from a different country than currently selected (which is pre-populated based on GeoIP and may not be the one you want to ship to) would leave the field blank as it wouldn't match any of the country areas for the currently selected country.

**Comment by primal100** [comment]
I made another commit but it's still not correct. But just wanted to brainstorm on here and see what you think.


It now uses a datalist. It works quite well except for one issue, where the autofill value doesn't exactly match a value in the list of choices. For example, the autofill value may say Dublin, but i18naddress only accepts Co. Dublin as a valid option.

If the autofill occurs for a different country then when the page refreshes to the new country's form the server side will try to guess the valid value, using the following code:

```python
    def format_value(self, value):
         value = super(DatalistTextWidget, self).format_value(value)
         value = value[0]
         if value:
             for choice in self.choices:
                 if any(c.lower() == value.lower() for c in choice):
                     return choice[0]
             for choice in self.choices:
                 if any(c.lower().startswith(value.lower()) for c in choice):
                     return choice[0]
             for choice in self.choices:
                 if any(value.lower() in c.lower() for c in choice):
                     return choice[0]
         return value
```

However if the autofill occurs and the country is the same the page  doesn't refresh so server side isn't an option. The user has to do the autofill and then click the dropdown to pick the correct value. It's not obvious for the enduser. If they don't select and just submit it won't be clear why it failed. 

It may be possible to write similar code as above in Javascript to try to find the correct value when an autofill event happens. There is an autofill event library:

https://github.com/tbosch/autofill-event

But I don't know how well it works across browers and so on, and you may not see it as a good option. So just wondering if anyone has any other ideas?

I'm thinking Ireland is a special case so another option for me is to modify i18naddress to not validate the country area and just accept whatever value the user inputs, as I trust the user to enter their country area correctly. I wonder is it something that could be provided as a configuration option?

**Comment by patrys** [comment]
I think it's ok to leave the user to correct "Dublin" to "Co. Dublin". The important part is that we do not clear the field so you can manually correct it. Not clearing the filed means that even if you're in a foreign country you should still be able to find the closest match.

**Comment by primal100** [comment]
I made another commit now, moving the "try to find a valid value" code to client side, running on a change event., with a 500ms delay, so it doesn't run when autofill with a country change occurs, until after the page reloads. It works well.

* When a country with no country area choices is selected, a regular input field is presented.
* When autofill is done on a country with country area choices, and there is no country change and hence no refresh, the change event will trigger to find a correct valid value for country area. So on Ireland, given Dublin, it changes to Co. Dublin automatically ( based on javascript includes).
* When United States is selected, and autofill is done changing country to Ireland, with Dublin as the country area, Dublin is sent as the country area value and returned from the server side as that. Due to 500ms delay, the "find a valid value" block of code will not run before the page refresh. Then when the page reloads with Ireland as the country, the initial value will still be Dublin. But the client side code will run trigger immediately to change it to Co. Dublin.
* When a user manually modifies the country area to a non-valid entry, the "find a valid value" block of code will run.

**Comment by patrys** [comment]
I'm not sure how I feel about "magic" heuristics like that. What will it do if multiple entries match? What if "Co" is entered for Ireland? And most importantly does "contains this substring" scale to non-latin alphabets (eg. Arabic, Chinese)?

We're dealing with shipping addresses here so I would personally feel much more confident if we had the user explicitly correct any vague fields instead of silently coercing and potentially shipping to a wrong province in a foreign country.

**Comment by primal100** [comment]
That's fair enough. What about a help-block if the value is invalid? This could be detected client side on a change event and give suggestions, like 

"Value is invalid. Did you mean: Co. Dublin"

Currently the server will return "This value is invalid for selected country" anyway. With a datalist this can be handled client side. Or is it better to do it server side and just return suggestions in addition to the error which is currently returned?

**Comment by patrys** [comment]
That could be a nice improvement but I don't think is required to get this merged as it could be added afterwards.

**Comment by primal100** [comment]
OK thanks. So in that case it's ready now, let me know what you think. Cheers

**Pull request merged**
