### PR TITLE
Redo the dashboard based on material design

### LINKED ISSUE #932: Fix images in product edit
- [x] When images are dropped in images view, new image card has wrong style.
- [x] Blinking information about dropping images

### LINKED ISSUE #933: Clickable rows in dashboard tables
Rows in tables should be used as links to item details/edit.

### LINKED ISSUE #938: Consistent use of CTA buttons
For displaying lists of objects in dashboard we use two kinds of Materialize components: collections or tables. We need to unify how we display CTA buttons (like adding new products, categories etc.) in these list views, because we have it mixed right now.
- Collections should always use Floating Action Buttons as primary actions ([link](https://material.io/guidelines/components/buttons-floating-action-button.html)).
- Tables should have buttons in the table's header ([link](https://material.io/guidelines/components/data-tables.html#data-tables-tables-within-cards)).

### LINKED ISSUE #939: Set max width for forms

### LINKED ISSUE #942: Context menu actions
Each edit view in dashboard should have one clearly visible call-to-action button. Additional actions (e.g. delete product, view in storefront) should be consistently moved to the context menu in the top right corner of the view ([link](https://material.io/guidelines/components/menus.html#menus-usage)).

Currently most of them are placed in breadcrumbs:
image
The context menu button should be placed inside the `subheader` container - the same container where breadcrumbs are.

### PR DESCRIPTION
**Pull request by patrys**
Just your average pull request at 3:30 am.

Todo:

* [x] Change main container padding
* [x] Test on mobile
* [x] Drop class override from materializecss templatetag
* [x] Primary buttons in forms should be visually distinguished (e.g. UPDATE button in product update view). This rule doesn't apply to:
    - destructive or dangerous actions (e.g. removing, refunding)
    - buttons in modals
* [x] Content should be vertically centered
* [x] Improve the appearance of empty lists - we should only show a message without any background and border, similar to "Drop images here..." message.
* [x] Add "cancel" button in site settings page (link to homepage)
* [x] "Add" buttons in data tables should be displayed if no row is select. "Delete" button should be displayed if any row is selected.
* [x] Drop filtering in customers view.
* [x] Move address edit forms to separate views.
* [x] Adjust width of modals to match with their content

Fixes #942
Fixes #939
Fixes #938 
Fixes #933
Fixes #932

### CODE REVIEW

**Comment by patrys** [comment]
## Before

image

## After

image

**Comment by patrys** [comment]
## Before

image

## After

image

**Comment by patrys** [comment]
## Before

image

## After

image

**Comment by patrys** [comment]
## Before

image

## After

image

**Comment by patrys** [comment]
## Before

image

## After

image

**Comment by krzysztofwolski** [comment]
Actions in table header (stock management) need script inspection.

**Comment by krzysztofwolski** [comment]
New dashboard looks better than Crysis. But I have found one thing to fix:

- [ ]  When views use table to display object list, and theres no objects, add button is missing (Found on Sales and Vouchers. Probably in other places too).

**Comment by weronka** [comment]
@krzysztofwolski fixed:

screenshot

**Pull request merged**
