### PR TITLE
Sitemap/feed domain

### LINKED ISSUE #1195: Sitemap always show: http://example.com
My sitemap.xml always show domain name as: http://example.com/ even I changed domain in dashboard - site settings to my domain.

### PR DESCRIPTION
**Pull request by bogdal**
This PR fixes the domain name in sitemap and google feed.

Fixes #1195

### CODE REVIEW

**Comment by elwoodxblues** [comment]
@bogdal Thanks for this PR. Now some parts of our code use either our own `SiteSettings` or `django.contrib.sites` to get the domain. In some places Django uses contrib.sites internally (e.g. in feeds, if I'm correct) and overriding it everywhere to use our settings would be cumbersome. I was thinking that saving our site settings in dashboard should also update current site from `django.contrib.sites`. This would solve these inconsistencies. What do you think @patrys @bogdal?

**Comment by bogdal** [comment]
I think we should always use the `SiteSettings` model because it doesn't require a restart of the application.

**Comment by elwoodxblues** [comment]
And having it in `django.contrib.sites` do require a restart? It is stored in model as well. I see that we're using contrib.sites also in this file: https://github.com/mirumee/saleor/blob/master/saleor/data_feeds/google_merchant.py

**Comment by bogdal** [comment]
`django.contrib.sites.model.Site` is cached at the module level. It's a problem when you have more than one project's instance. In my opinion we should use only `SiteSettings` and update the above code as well.

**Comment by patrys** [comment]
As @bogdal wrote, Site objects are cached indefinitely and there's no way to invalidate the cache once the model changes. We could however merge the two models and have a middleware clear the site cache at the beginning of each request.

**Comment by mociepka** [comment]
@krzysztofwolski we have the same issue in your current project. How we solve that?

**Comment by bogdal** [comment]
@elwoodxblues I have just fixed data feeds as well.

**Comment by elwoodxblues** [comment]
Thanks @bogdal

**Comment by elwoodxblues** [comment]
We'll take different approach to this problem, for details please take a look at issue #1213 and PR #1214

**Pull request closed without merging**
