### PR TITLE
Update products.py

### PR DESCRIPTION
**Pull request by MatthewBosek**
I want to merge this change because...

Product.availability and ProductVariant.availability have incorrect deprecation message #4320

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] Database migration files are up to date.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] GraphQL schema and type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by django-queries** [comment]
Here is the report for 53b36070303f2c6d149068f366a1baa40b34100f (MatthewBosek/saleor @ master)
Base comparison is f233f200147d06f739cd8594d9cfa26d03c52a58.



<details><summary>No differences were found. (click me)</summary>
<p>

```diff
# api.benchmark checkout
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  add billing address to checkout     	         34	         34	             20
  add shipping to checkout            	          7	          7	              0
  checkout payment charge             	         14	         14	              0
  complete checkout                   	          6	          6	              0
  create checkout                     	         48	         48	             24

# api.benchmark homepage
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  retrieve main menu                  	          5	          5	              0
  retrieve product list               	          4	          4	              0
  retrieve secondary menu             	          5	          5	              0
  retrieve shop                       	          2	          2	              0

# api.benchmark product
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  product details                     	         13	         13	              3

# api.benchmark variant
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  retrieve variant list               	          9	          9	              2
```

</p>
</details>

**Comment by NyanKiyoshi** [comment]
Thanks for your contribution! There is the below one as well. Could you change it?
https://github.com/mirumee/saleor/blob/b0334726d4e1a1b51eed933e7a71d27ec92a8dcc/saleor/graphql/product/types/products.py#L185

**Comment by maarcingebala** [comment]
Hey @MatthewBosek, thanks for opening the PR! If you see at the checks above, [the CI is failing](https://travis-ci.org/mirumee/saleor/builds/568618686?utm_source=github_status&utm_medium=notification) with Black and outdated GraphQL schema. To fix that you need to update the schema as @NyanKiyoshi suggested above (you can do that as well with the command `npm run build-schema`). [Black](https://github.com/psf/black) is the tool for Python code formatting that we use. You need to install it locally and run apply it to the files you've edited.

**Comment by MatthewBosek** [comment]
@maarcingebala @NyanKiyoshi I have done both: performed the schema update and used the Black tool to format the code. How do I perform a pull request? I am new to this.  Thanks!

**Pull request closed without merging**
