### PR TITLE
Install pywatchman for local development

### PR DESCRIPTION
**Pull request by patrys**
This prevents `manage.py` from [repeatedly checking all loaded files for changes while running](https://docs.djangoproject.com/en/3.0/ref/django-admin/#runserver).

Please test this before merging, especially on systems that do not have `watchman` installed. We may need to update our docs.

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by maarcingebala** [comment]
I installed `pywatchman` locally without having `watchman` and `runserver` worked normally. Maybe we can merge this and if any issues with installations are reported, we'll fix them then?

**Comment by fowczarek** [comment]
@maarcingebala Maby should we test it on Windows before merge?(I'm tested it on my Ubuntu 18.04)

**Comment by IKarbowiak** [comment]
I checked on Windows. Works correctly.

**Comment by patrys** [comment]
Rebased on current master (poetry conflict).

**Pull request merged**
