### PR TITLE
Unify Template Names

### PR DESCRIPTION
**Pull request by UsmanAhmadSaeed**
I want to merge this change because...

#2448 
### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] Database migration files are up to date.
1. [ ] The changes are tested.
1. [ ] GraphQL schema and type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

PS: I'm unsure if anything will break or not. Being a newbie to programming and open source, I've just changed filenames as mentioned in the issue #2448

### CODE REVIEW

**Comment by maarcingebala** [comment]
Hey, thanks for opening the PR. Could you also make sure that all the tests are passing? If you see at the checks above, Travis CI is failing now.

**Comment by maarcingebala** [comment]
@UsmanAhmadSaeed Bump, see my comment above ⬆️. Let me know if you're going to work on this. If not, maybe someone else can take this issue.

**Comment by UsmanAhmadSaeed** [comment]
@maarcingebala I'm sorry but I'm not skilled enough to resolve that issue. And apologies for the delayed response.

**Comment by maarcingebala** [comment]
@UsmanAhmadSaeed, in the output from `pytest` you can find names of failing tests and exceptions. From what I see, all of them are `TemplateDoesNotExist` errors and they come from view functions. It means that the view functions are still referring to the old names, that this PR removes. We would need to update those references as well. I'll keep the PR open - If you have time and will, give it a try!

**Comment by NyanKiyoshi** [comment]
Closing in favor of #4867. Thank you for your contribution!

**Pull request closed without merging**
