### PR TITLE
1082 add social media links

### LINKED ISSUE #1082: Add links for more social media platforms
The `base.html` template currently has only limited support for social media links. Currently only Github and Twitter are built-in and are added using specific `.svg` files:

```
<a target="_blank" rel="noopener" class="github-footer" href="https://github.com/mirumee/saleor">
  <svg data-src="{% static "images/github_logo.svg" %}" width="45px" height="45px"/>
</a>
<a target="_blank" rel="noopener" href="https://twitter.com/getsaleor">
  <svg data-src="{% static "images/twitter_logo.svg" %}" width="45px" height="45px" />
</a>
```

One way to support all major social media platforms would be through the integration of [Font Awesome](http://fontawesome.io). This would also allow developers to use the many other FA icons in their stores.

### PR DESCRIPTION
**Pull request by amorphic**
Adds example links for several popular social media platforms to the `base.html` template. Uses Saleor-specific links where available, otherwise Mirumee links.

image

The individual icon svgs for Twitter and Github are replaced by [Font Awesome](http://fontawesome.io) meaning devs can also now include other FA icons in their shops.

Fixes #1082

### CODE REVIEW

**Comment by patrys** [comment]
Font Awesome, while being awesome, also adds quite a bit to both `node_modules` size and the initial page download size. I think we'd prefer to use individual SVG files where possible.

There's a number of other reasons listed in https://github.com/blog/2112-delivering-octicons-with-svg

**Comment by amorphic** [comment]
@maxwhosevillage yep @patrys makes a good point in his comment above.

My plan is to retain the links to the various social networks but revert to SVGs as suggested. I've been working on a separate PR to fix #1080 so once that one's up for review I'll make the required changes to this one and hopefully get it merged.

**Comment by patrys** [comment]
👍 Looking forward to merging this when complete!

**Comment by amorphic** [comment]
@patrys @maxwhosevillage it's taken me a while to get around to this but as requested I've removed FA and created the same social links using svg logos. I also renamed a couple of the existing logo svgs for consistency.

Let me know if there's anything else you'd like changed before this can be merged.

**Comment by patrys** [comment]
Personally I'd prefer dashes instead of underscores in file names but otherwise it looks good!

**Pull request merged**
