### PR TITLE
fix #4158 rozor typo to razor

### LINKED ISSUE #4158: Typo in Payment Gateway 'razorpay'
### What I'm trying to achieve
…
Typo in Payment razorpay. https://github.com/mirumee/saleor/blob/0cf515b36501f341fda8f3310c6f0f570e6a5350/saleor/payment/gateways/razorpay/forms.py#L13

https://github.com/mirumee/saleor/blob/0cf515b36501f341fda8f3310c6f0f570e6a5350/saleor/payment/gateways/razorpay/forms.py#L16
### Steps to reproduce the problem
1. N/A

### What I expected it to be
…
Razorpay instead of Rozorpay
### Screenshots

**System information**
Operating system: N/A
Browser: N/A

### PR DESCRIPTION
**Pull request by mainanick**
I want to merge this change because...

This PR fixes #4158 all 84  typo occurrences. 'Rozorpay' typo to 'Razorpay'
### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] Database migration files are up to date.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] GraphQL schema and type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by NyanKiyoshi** [comment]
@patrys is it okay to directly edit the pot files?

**Comment by maarcingebala** [comment]
I'm not sure, but I think it's enough to change the occurrence in Python code and the rest of it should be updated as part of the periodic translations sync.

**Comment by patrys** [comment]
There's no point to edit the localization files as they are automatically generated but it will do no harm.

**Comment by maarcingebala** [comment]
So let's merge it as it is. Thanks for opening the PR @mainanick!

**Pull request merged**
