### PR TITLE
Translation into german

### PR DESCRIPTION
**Pull request by maxwhosevillage**
We are using saleor in a project and found that german is missing.

therefore i made the translation.

i'ld love to see some review and german added to the supported languages.

### CODE REVIEW

**Comment by weronka** [comment]
@maxwhosevillage Thanks for sharing! Also we use [Transifex platform](https://www.transifex.com/mirumee/saleor-1/dashboard/) for managing translations. Will be cool if you'll join Saleor project and add your work there. 

Also please remove `fuzzy` messages from added .po files.

**Comment by maxwhosevillage** [comment]
Thanks weronka

I deleted the fuzzy and requested german in transifex.
lokking forward to contribute to the project

**Comment by patrys** [comment]
@maxwhosevillage Thank you for dedicating your time to Saleor! I was away for two weeks in Korea but I've now added German as a language on Transifex. Please join the German team and upload the translation files there so you can take credit for your work while allowing others to improve the translations as Saleor evolves. Once the translation files are there, we can merge them into this repository automatically.

**Comment by maxwhosevillage** [comment]
Thanks you for your reply. Hope you enjoyed your time in Korea.

I uploaded the files to Transifex and added some missing translations.
I would really appreciate to see sailor adding support for the german language.

**Comment by patrys** [comment]
I've merged the translations from Transifex. Gettext complains however that some of the format strings don't contain the original interpolation placeholders (`%(foo)s` and such) and I've noticed that each "are you sure" question seems to use a different grammatical form.

**Comment by maxwhosevillage** [comment]
I think it's done with ac8e8ec8970c2e4edb68d59c5d1cb3b46ee8a33d

**Comment by patrys** [comment]
@maxwhosevillage Please see my comment above, the translations are not currently usable as they don't pass validation. Try running `python manage.py compilemessages -l de` to see a list of errors.

**Comment by maxwhosevillage** [comment]
@patrys Now i got some time and want to get the german translation done.
I can't figure out how to get the errors.
if I run  `python manage.py compilemessages -l de` I get:
```
python manage.py compilemessages -l de                                                           
processing file django.po in /Users/max/Documents/PyCharmProjects/saleor/locale/de/LC_MESSAGES
processing file djangojs.po in /Users/max/Documents/PyCharmProjects/saleor/locale/de/LC_MESSAGES
processing file django.po in /Users/max/Documents/PyCharmProjects/saleor/saleor/dashboard/locale/de/LC_MESSAGES
```
 how can i merge the translation from transifex?
Thanks for any help

**Comment by rapwie** [comment]
I just joined the project on transifex and don't know how to fix the errors
just give me a hint please

**Comment by patrys** [comment]
I'm getting the following errors:

```
CommandError: Execution of msgfmt failed: /Users/patrys/GitHub/mirumee/saleor/locale/de/LC_MESSAGES/django.po:76: format specifications in 'msgid_plural' expect a tuple, those in 'msgstr[0]' expect a mapping
/Users/patrys/GitHub/mirumee/saleor/locale/de/LC_MESSAGES/django.po:2346: a format specification for argument 'last_order' doesn't exist in 'msgstr'
/Users/patrys/GitHub/mirumee/saleor/locale/de/LC_MESSAGES/django.po:2797: a format specification for argument 'tracking' doesn't exist in 'msgstr'
/Users/patrys/GitHub/mirumee/saleor/locale/de/LC_MESSAGES/django.po:3577: a format specification for argument 'stock_count', as in 'msgstr[1]', doesn't exist in 'msgid_plural'
/Users/patrys/GitHub/mirumee/saleor/locale/de/LC_MESSAGES/django.po:3984: a format specification for argument 'order' doesn't exist in 'msgstr'
msgfmt: found 6 fatal errors
```

I'll push in a minute with updated translation files.

**Comment by rapwie** [comment]
just fixed it in separate pr #1063

**Comment by maxwhosevillage** [comment]
Maybe we can close this request and continue to work on transifex.
@patrys and @rapwie Thanks a lot for the patience

**Comment by patrys** [comment]
Yes, let's move this to Transifex and finish there.

**Pull request closed without merging**
