### PR TITLE
Drop creating an avatar in create and update staff mutation

### LINKED ISSUE #5442: Drop creating an avatar in create and update staff mutations.
### What I'm trying to achieve
Drop creating an avatar in creating and update staff mutations.

### Steps to reproduce the problem
1. Create a staff user without avatar or update user without avatar
2. Avatar is created

### What I expected to happend
Don't create an avatar when the user doesn't have one.

### Screenshots

**System information**
Operating system:

### PR DESCRIPTION
**Pull request by kswiatek92**
closes #5442

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations

# Pull Request Checklist

* [x] Privileged queries and mutations are guarded by proper permission checks
* [x] Database queries are optimized and the number of queries is constant
* [x] Database migration files are up to date
* [x] The changes are tested
* [x] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by maarcingebala** [comment]
I think we also want to drop the `get_random_avatar` and all its occurrences as we want to use these avatars only in frontend. Then we can also drop `AVATARS_PATH` and `saleor/static/images/avatars` dir.

**Comment by kswiatek92** [comment]
@maarcingebala don't we want to use `get_random_avatar` in populatedb?

**Comment by maarcingebala** [comment]
@kswiatek92 We want to render them entirely in the frontend.

**Comment by maarcingebala** [comment]
@kswiatek92 CI is failing.

**Pull request merged**
