### PR TITLE
[WIP][Help wanted] Upgrade version of elasticsearch from 5.x -> 6.x

### PR DESCRIPTION
**Pull request by stephenmoloney**
What does this commit/MR do?

- Upgrade version of elasticsearch from 5.x -> 6.x

Why is this commit/MR needed?

- To upgrade elasticsearch version
- Most kubernetes deployments are using 6.x rather than 5.x meaning that
it is harder to setup a helm kubernetes for 5.x

I want to merge this change because...

I would like to have elasticsearch 6.x, primarily because most recent charts for helm 
are for elasticsearch 6.x

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).

### CODE REVIEW

**Comment by stephenmoloney** [comment]
Help wanted.

**Comment by stephenmoloney** [comment]
Gonna try and see if can get older version of elasticsearch chart functional. Will reopen if get stuck. Closing for time being.

**Comment by NyanKiyoshi** [comment]
@stephenmoloney it probably would be easier to open an issue where we could put some sort of roadmap/ list of issues preventing Saleor to upgrade to 6.x.

**Comment by stephenmoloney** [comment]
@NyanKiyoshi I have planned that.
I don't want to open it too early.
There will be some changes I will suggest for settings.py and possibly uwsgi.ini

I'm holding off until it's a bit more mature.

**Pull request closed without merging**
