### PR TITLE
Change max length of SKU to 255

### LINKED ISSUE #4389: Current Product Variant SKU is too short
### What I'm trying to achieve
We have some products that may be made up of a number of SKU's combined into a single product. Whilst creating product "bundles" multiple products or variants tied into a single object could be an ideal solution, I can see this being niche feature that could cause complexity not just from a data modelling perspective but also from an admin UX perspective may provide little in the way of benefits for other developers.

### Describe a proposed solution
Instead, I would propose that a simple change to increase the ProductVariant sku field from 32 characters to somewhere in the region of 100 characters.

I don't really foresee any instances where this would cause breakages of current sites and it would be nice to have this standardised in the Saleor code base to remove the need for merge migrations and the like.

### PR DESCRIPTION
**Pull request by lex111**
I want to merge this change because...

Resolves #4389

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [x] Database migration files are up to date.
1. [x] The changes are tested.
1. [x] GraphQL schema and type definitions are up to date.
1. [x] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by django-queries** [comment]
Here is the report for fff0b6eefd014ef3d46be30f4f26f14238d2ebad (lex111/saleor @ sku-255)
Base comparison is d54fd99d20c833321d5ce02154d3f15881b14222.



<details><summary>No differences were found. (click me)</summary>
<p>

```diff
# api.benchmark checkout
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  add billing address to checkout            	         34	         34	             20
  add shipping to checkout                   	          7	          7	              0
  checkout payment charge                    	         14	         14	              0
  complete checkout                          	          6	          6	              0
  create checkout                            	         48	         48	             24

# api.benchmark homepage
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  retrieve main menu                         	          5	          5	              0
  retrieve product list                      	          4	          4	              0
  retrieve secondary menu                    	          5	          5	              0
  retrieve shop                              	          2	          2	              0

# api.benchmark product
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  product details                            	         15	         15	              3
  retrieve product attributes                	         13	         13	              2

# api.benchmark variant
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  retrieve variant list                      	         18	         18	              8

# api product sorting attributes
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  sort product not having attribute data     	         21	         21	              0
```

</p>
</details>

**Comment by maarcingebala** [comment]
Thanks for opening the PR! Changes look good but there are two minor things to fix:
- please apply [Black](https://pypi.org/project/black/) to your changes (it's failing on CI now),
- update the `CHANGELOG.md` by adding an entry in the "Unreleased" section with the description of your changes, a number of the PR and you Github handle (see at other entries).

**Comment by maarcingebala** [comment]
🎉 Thanks for your contribution and for participating in Hacktoberfest! Please send me your shipping address to `marcin@mirumee.com` and we'll send you our Ultra-Fast Socks:

EF328rvXYAggNhc

**Comment by lex111** [comment]
@maarcingebala thanks to you, too! I really wanted to update Russian localization, there are enough mistakes, but I can not test this locally via Docker. I understand that you are using Transifex, but I cannot change and see update locale? In general, would it be easier for me to open a PR with my edits rather than to do this on Transifex, or can I upload my file (*.po) into this service?

**Comment by NyanKiyoshi** [comment]
@lex111 I believe you should be able to do it, I don't think there is special permissions to be able to. That's how I used to do: https://docs.transifex.com/translation/importing-translations

**Comment by lex111** [comment]
@NyanKiyoshi cool, I’ll definitely try when I finish the translation. But it’s bad that now I can’t see my changes locally :(

**Pull request merged**
