### PR TITLE
Update payment information before processing payment

### PR DESCRIPTION
**Pull request by Boquete**
I want to merge this change because in authentication / processing payment, order information is essential 

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] Database migration files are up to date.
1. [ ] The changes are tested.
1. [ ] GraphQL schema and type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by patrys** [comment]
@Boquete Can you describe the use case where this becomes useful? We explicitly try to avoid placing orders without a valid payment method.

**Comment by Boquete** [comment]
> @Boquete Can you describe the use case where this becomes useful? We explicitly try to avoid placing orders without a valid payment method.

I've seen recently issue reported that someone needed it in some payment integration gateway.

In our case, which is PayU, we need order details to authorize payment, in which redirect url is generated for payu site.

But you are right, placing order without valid payment method is not a great idea too. Not sure which one is worse, but placing order without valid payment method looks less scary, then not allowing other gateways to be implemented. Maybe there is some compromise (?)

**Comment by Boquete** [comment]
> > @Boquete Can you describe the use case where this becomes useful? We explicitly try to avoid placing orders without a valid payment method.
> 
> I've seen recently issue reported that someone needed it in some payment integration gateway.
> 
> In our case, which is PayU, we need order details to authorize payment, in which redirect url is generated for payu site.
> 
> But you are right, placing order without valid payment method is not a great idea too. Not sure which one is worse, but placing order without valid payment method looks less scary, then not allowing other gateways to be implemented. Maybe there is some compromise (?)

Related issue : https://github.com/mirumee/saleor/issues/5193

**Comment by patrys** [comment]
In the case where you need a redirect URL ahead of the time, you can use the Payment ID or the Checkout token in the return URL and then redirect to the appropriate order which should already exist by the time the redirect happens.

**Comment by maarcingebala** [comment]
Thanks for opening the PR, but the issue should be solved in https://github.com/mirumee/saleor/issues/5193. Also, we don't want to change the flow where payment is required to create orders. As @patrys wrote, we don't want to have unpaid orders in the system.

**Pull request closed without merging**
