### PR TITLE
Templatetag with saleor version

### PR DESCRIPTION
**Pull request by krzysztofwolski**
It's easier to include this as template.

### CODE REVIEW

**Comment by patrys** [comment]
This template is not used anywhere though. I'm sure someone will remove it in two weeks during cleanup. Not sure why it's a template, why in dashboard and why with a txt extension.

**Comment by krzysztofwolski** [comment]
> Not sure why it's a template
It's a label visible in dashboard not something used in code. So i treat it as template

> why in dashboard
Because it's only place where it is displayed
 
> why with a txt extension
Wanted to avoid creating context processor only used on our demo page.

**Comment by krzysztofwolski** [comment]
As I talked with @bogdal, maybe template tag would be better solution.

**Comment by krzysztofwolski** [comment]
Done

**Comment by patrys** [comment]
Can we make the template tag visible to all superusers?

**Comment by krzysztofwolski** [comment]
@patrys Done

**Pull request merged**
