### PR TITLE
[WIP] Implement order list and parts of order details

### LINKED ISSUE #2639: Implement order section in dashboard
Connect order section components to API and add them to the dashboard side menu, to make orders manageable.

### PR DESCRIPTION
**Pull request by patrys**
⚠️ Work in progress!

Fixes #2639 

Re #2587 

### TODO
* [x] phone numbers returned as single string while input expects prefix + number #2765
* [x] Order type does not have subtotal #2764
* [x] Order type does not have total authorized #2763
* [x] ~~Order type does not have total refunded (and neither does the Payment model)~~
* [x] order lines do not provide a mechanism to ask for a product thumbnail #2858
* [x] payment statuses are not an enum #2744
* [x] there are no order event types #2154 
* [x] there is a function called `Ø` that could probably use a better name
* [x] order summary uses fixed-height boxes with all labels grouped in one div and all values in another (this breaks when we need to show additional rows and is terrible for a11y) #2861
* [x] shipping method dialog is named "Edit customer details"
* [x] ~~it's impossible to select anything from the list of shipping methods without typing first~~
* [x] shipping method selection dialog does not indicate the previous value
* [x] there's no way I found to edit either of the addresses #2862
* [x] order cancellation can be repeated even if order was already cancelled #2808
* [x] there's no UI to select whether stock should be restored on cancellation #2868
* [x] `onCustomerEmailClick` sounds like it should really just be an `<a href="mailto:...">` #2869
* [x] `fulfillmentCreate(input: { order: ID!, ... })` should be `orderCreateFulfillment(order: ID!, input: ...)` and should return `order` #2809
* [x] there's no "success" confirmation of any of the operations, be it a visual cue or an explicit toaster message 
* [x] `orderAddNote` should take `order: ID!` an argument and should return `order` #2810
* [x] `Form` > `OrderFulfillmentDialog` should become `OrderFulfillmentDialog` > `OrderFulfillmentForm` > `Form`
* most mutations are not connected:
    * [x] cancel order
    * [x] customer edit - UI is not connected to a callback #2870
    * [x] add product #2854
    * change shipping method
        * [x] UI is not connected to a callback #2867
        * [x] mutation missing #2807 
    * [x] fulfillment - UI is not connected to a callback
    * [x] capture - UI is not connected to a callback
    * [x] refund - UI is not connected to a callback
    * [x] void
    * [x] add order note - UI is not connected to a callback #2866

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).

### CODE REVIEW

**Comment by dominik-zeglen** [comment]
Very nice work with `Ø` function! But I feel like it should be introduced in separate PR, since this is project-wide change.

**Comment by maarcingebala** [comment]
@dominik-zeglen Eventually this function will be used across the whole project, but extracting a separate PR now would only add extra work and dependencies between PRs which slows us down. I think we can as well introduce it incrementally.

**Comment by dominik-zeglen** [comment]
Blocked by #2849

**Comment by dominik-zeglen** [comment]
Blocked by #2854

**Pull request merged**
