### PR TITLE
fixed errors from compilemessages

### PR DESCRIPTION
**Pull request by rapwie**
for reference https://github.com/mirumee/saleor/pull/1032

### CODE REVIEW

**Comment by patrys** [comment]
Would you mind fixing those on Transifex instead? Translation files in the repository are overwritten when I synchronize translations.

https://www.transifex.com/mirumee/saleor-1/language/de/

**Comment by rapwie** [comment]
I fixed those on transifex!

**Comment by patrys** [comment]
`master` branch now contains a working German translation! 🎊

**Comment by rapwie** [comment]
Nice!

**Pull request closed without merging**
