### PR TITLE
Missing language in settings

### PR DESCRIPTION
**Pull request by patrys**
When submitting #4479 I forgot to include the settings file

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] Database migration files are up to date.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [x] GraphQL schema and type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by django-queries** [comment]
Here is the report for ff4c3907edc8c9dea8e79c63d2affb3344f40639 (patrys/saleor @ sync-transifex)
Base comparison is c0984137c26304a1d0bd9b22cb6d31e48039959b.



<details><summary>No differences were found. (click me)</summary>
<p>

```diff
# api.benchmark checkout
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  add billing address to checkout     	         34	         34	             20
  add shipping to checkout            	          7	          7	              0
  checkout payment charge             	         14	         14	              0
  complete checkout                   	          6	          6	              0
  create checkout                     	         43	         43	             21

# api.benchmark homepage
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  retrieve main menu                  	          5	          5	              0
  retrieve product list               	          4	          4	              0
  retrieve secondary menu             	          5	          5	              0
  retrieve shop                       	          2	          2	              0

# api.benchmark product
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  product details                     	         13	         13	              3

# api.benchmark variant
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  retrieve variant list               	          9	          9	              2
```

</p>
</details>

**Comment by maarcingebala** [comment]
@patrys GraphQL schema was not updated here.

**Comment by maarcingebala** [comment]
@patrys Is this intended to add GraphQL descriptions to our types with this PR? I'm fine with that but I'm also wondering why it was generated now and we never had them before?

**Comment by patrys** [comment]
@maarcingebala That's what the current version of Apollo tools outputs. I guess they were never regenerated after the version bump?

**Comment by maarcingebala** [comment]
@dominik-zeglen I need your input here. I just want to make sure that everyone has the same version of the tooling and won't accidentally remove those comments in the next PR by someone else.

**Comment by dominik-zeglen** [comment]
Hm to be honest I thought that comments come from newer version of `apollo` but mine generates types without them. @patrys which version do you use? I've got `2.15.0` installed.

**Comment by patrys** [comment]
2.15.0, prior to generating those I did a fresh `npm install` while @dominik-zeglen was looking at my screen 😄

**Comment by maarcingebala** [comment]
@patrys We suspect that the descriptions were generated because your `codegen` fetched the schema from Apollo Engine and not from the local `schema.graphql`. We prefer to stick to the local schema file, as our Apollo Engine isn't configured to get automatic updates of the schema.

**Comment by patrys** [comment]
@maarcingebala In that case, can anyone else rebuild the types? I don't know how to disable Apollo Engine integration, even commenting out the project name does not stop it from generating the same output.

**Comment by dominik-zeglen** [comment]
I'll do it then

**Pull request merged**
