### PR TITLE
Add partial product search

### PR DESCRIPTION
**Pull request by d-wysocki**
I want to merge this change because...I want to add partial product search

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by patrys** [comment]
What's the use case? What if I don't want this behavior?

**Comment by d-wysocki** [comment]
> What's the use case? What if I don't want this behavior?

@patrys For example if you had product with name `monsterblack` and you will type only `monster` into search field. You cannot turn off this functionality, we could add flag for this it will be necessary.

**Comment by patrys** [comment]
Why not let the client build the query and document how operators work?

**Comment by maarcingebala** [comment]
I'm not familiar with the operators, how would it look like in the API for example?

**Comment by patrys** [comment]
https://www.postgresql.org/docs/current/textsearch-controls.html

Examples:

* `products(filter: { search: "foo & bar" }, ...)` - containing both "foo" and "bar"
* `products(filter: { search: "foo | bar" }, ...)` - containing "foo" or "bar"
* `products(filter: { search: "!foo" }, ...)` - not containing "foo"
* `products(filter: { search: "foo:A | bar:B" }, ...)` - title (weight A) containing "foo" or description (weight B) containing "bar"
* `products(filter: { search: "foo:*" }, ...)` - containing a word starting with "foo"
* `products(filter: { search: "foo & (bar | baz)" }, ...)` - using parenthesis to override operator precedence

**Comment by maarcingebala** [comment]
Actually, that would be pretty awesome, but I have no idea how much work it would be. Seems like we should just pass the phrase from API directly to Postgres. There should be also some error handling when the user passes an invalid phrase, in which case we should raise some GraphQLError.

**Comment by patrys** [comment]
It seems the syntax is already handled if we drop the `:*` change (current implementation won't work if you search using two words). Not sure how syntax errors are handled.

**Review by tomaszszymanski129 — APPROVED** [review]

**Comment by maarcingebala** [comment]
We won't have time in the nearest future to improve this solution as discussed above. Should I close the PR for now?

**Comment by patrys** [comment]
Task linked: [SALEOR-2495 Add partial search to SearchVector in product](https://app.clickup.com/t/2549495/SALEOR-2495)

**Pull request closed without merging**
