### PR TITLE
Add `is_published` flag to Collection

### PR DESCRIPTION
**Pull request by apsummers**
Hi Saleor! First time trying out your project, and first PR here.

This PR addresses #1878 and adds an `is_published` field to the Collection model. Here are a few relevant screenshots of the feature

Dashboard Collection list displays visibility and adds `is_published` to filters:

screen shot 2018-04-22 at 3 26 49 pm

"Published" toggle on side in Collection detail like in Product detail:

screen shot 2018-04-22 at 3 26 58 pm

Admins can preview unpublished collections on the site with a warning:

screen shot 2018-04-22 at 3 27 46 pm

Regular users 404 on unpublished Collections:

screen shot 2018-04-22 at 3 28 00 pm

**Still TODO:** The bottom menu still shows unpublished collections and links to them, which 404. Menu items seem to be created in the Dashboard, so maybe that's intended? I haven't fully wrapped my head around the Menu yet, so please suggest the right approach here.

I also saw the discussion of a naming convention on the Issue. My 2 cents as a Magento developer in my day job:

Products (and by extension Collections) seem to feel most natural as "Enabled/Disabled" (as it is in Magento). "Published/Not Published" gives off more of a "written content" feel, which seems appropriate for Pages. I used `is_published` for these changes as that's what Product uses already but I would be happy to change it to whatever you all think is most appropriate.

Saleor seems like a very cool project!

### Pull Request Checklist

(Please keep this section. It will make maintainer's life easier.)

1. [x] Privileged views and APIs are guarded by proper permission checks.
1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Database queries are optimized and the number of queries is constant.
1. [x] The changes are tested.
1. [x] The code is documented (docstrings, project documentation).
1. [x] Python code quality checks pass: `pycodestyle`, `pydocstyle`, `pylint`.
1. [x] JavaScript code quality checks pass: `eslint`.

### CODE REVIEW

**Comment by elwoodxblues** [comment]
Hi @apsummers, thanks a lot for this PR! I've read through the code and everything seems fine.

You're right about menu entries linking to unpublished pages/collections. There is no restriction for that, but I guess as long as they return 404 and not reveal the hidden content, it should be fine for now. We can open a separate issue to discuss it.

Also, I like your thoughts about proper naming of those flags. We could have `is_enabled` for products/collections and `is_published` for written content. If you have time, it would be great if you could improve the naming as you suggested. If not, I'll open an issue to fix it later and we'll merge your PR as it is.

**Comment by Pacu2** [comment]
@elwoodxblues I think it should be forbidden to assign not published Collections to MenuItems, what's more, they should be excluded from the suggestions.

**Comment by elwoodxblues** [comment]
@apsummers We prefer multiple commits for a better trace of changes. For the migrations, we try to introduce as few as possible with each PR, so you can recreate them once you've changed the models.

**Comment by Pacu2** [comment]
@apsummers We would like to include this change in April's release, please let me know if you will find time, or we shall take care of it.

Scope of this PR is to be discussed, for me just fixing the isort issue is fine. Rest can be handled in separate issues

**Comment by apsummers** [comment]
Hey @Pacu2, sorry about the wait! I'm a little busy for the rest of the week, so I've fixed the isort issue. Feel free to merge whenever you're ready :+1:

**Comment by Pacu2** [comment]
@apsummers Nicely done, thanks for the contribution!
good_job

**Pull request merged**
