### PR TITLE
Add message when product is deleted from cart

### LINKED ISSUE #718: Add success message after deleting item from cart

### PR DESCRIPTION
**Pull request by szewczykmira**
Closes #718

### CODE REVIEW

**Comment by artursmet** [comment]
@szewczykmira it doesn't work as expected - alert shows up after modifying cart quantity, but after deleting a product it's not visible at all.

**Comment by artursmet** [comment]
Maybe @weronka may help with it?

**Comment by artursmet** [comment]
@szewczykmira Please rebase with demo-store branch

**Comment by szewczykmira** [comment]
@artursmet done

**Pull request merged**
