### PR TITLE
 Check whether PRs GraphQL schema and the migrations are up to date 

### LINKED ISSUE #4122: The payments migrations are out of date
The payments transaction kind dropped the charge kind in #4098, we should migrate them to `CAPTURE`.

### PR DESCRIPTION
**Pull request by NyanKiyoshi**
Fixes #4122.

### GraphQL Schema
```
check_gql_schema run-test: commands[0] | sh -c './manage.py get_graphql_schema | diff saleor/graphql/schema.graphql -'
WARNING: test command found but not installed in testenv
  cmd: /bin/sh
  env: /home/travis/build/NyanKiyoshi/saleor/.tox/check_gql_schema
Maybe you forgot to specify a dependency? See also the whitelist_externals envconfig setting.
DEPRECATION WARNING: this will be an error in tox 4 and above!
2591d2590
<   CHARGE
ERROR: InvocationError for command /bin/sh -c './manage.py get_graphql_schema | diff saleor/graphql/schema.graphql -' (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   check_gql_schema: commands failed
```

### Migrations
```
check_migrations run-test: commands[2] | python manage.py makemigrations --dry-run --check
Migrations for 'payment':
  saleor/payment/migrations/0011_auto_20190516_0910.py
    - Alter field kind on transaction
ERROR: InvocationError for command /home/travis/build/NyanKiyoshi/saleor/.tox/check_migrations/bin/python manage.py makemigrations --dry-run --check (exited with code 1)
```

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [x] Database migration files are up to date.
1. [x] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [x] GraphQL schema and type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by jxltom** [comment]
It will be nice to also check the typescript types, which are generated by ```npm run build-types```, are also up to date.

**Comment by NyanKiyoshi** [comment]
I'm not sure if there is a proper way to check that with codegen? If there is not, we need to check for file changes (through git, as easy as that).

**Comment by jxltom** [comment]
I'm not so familar with it, but I didn't find any such functions in https://github.com/apollographql/apollo-tooling.

**Comment by maarcingebala** [comment]
I've asked @dominik-zeglen and apparently, there is no way to achieve checking types with codegen.

**Pull request merged**
