### PR TITLE
Truncate user name in dashboard to avoid line break.

### PR DESCRIPTION
**Pull request by cridenour**
Uses the truncatechars template tag to avoid line breaks in the dashboard sidebar.

### CODE REVIEW

**Comment by patrys** [comment]
Wouldn't `class="truncate"` work better here?

**Comment by cridenour** [comment]
The styles of the menu expect inline, so we would need to add an additional class to set it to inline-block as well as the custom width. This seemed the simpler solution.

**Comment by patrys** [comment]
Agreed it's simpler this way but with certain letters it may look weird (22 letters "w" are not the same width as 22 letters "i" etc.).

**Comment by cridenour** [comment]
That's fair. 21 'W's will definitely not fit. I'll update my branch.

**Comment by weronka** [comment]
We are redesigning side navigation and header areas. Changes preventing user name overflowing will be merged in other pull request.

**Pull request closed without merging**
