### PR TITLE
Fix country area choices

### LINKED ISSUE #3764: Duplicate choices in shipping address
### What I'm trying to achieve
I'm trying to set shipping user for Russian user and there are duplicate values in "Oblast" selector.

### Steps to reproduce the problem
1. Create new shipping address
2. Country --> Russia
3. There are duplicated values in "Oblast" selector

### What I expected to happen
There are no duplicated values in "Oblast" selector

### Screenshots
What happens now

What I expect to see

**System information**
Operating system: Manjaro Linux
Browser: Google Chrome 72.0.3626.81

### PR DESCRIPTION
**Pull request by fowczarek**
I want to merge this change because resolve #3764

### Pull Request Checklist

1. [x] Privileged views and APIs are guarded by proper permission checks.
1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Database queries are optimized and the number of queries is constant.
1. [x] Database migration files are up to date.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [x] GraphQL schema and type definitions are up to date.
1. [x] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by jxltom** [comment]
It will be nice to solve it for API side as well.

**Comment by maarcingebala** [comment]
@fowczarek Can we fix this in API as well?

**Comment by fowczarek** [comment]
@maarcingebala @jxltom 
Where does this error occur in API?

**Comment by jxltom** [comment]
If I recall correctly, the ```addressValidator``` API also returns duplicated ```country_area``` fields as well.

**Comment by fowczarek** [comment]
From my point of view API working correctly, because we allow users to input country area name in many formats as the latin alphabet or local alphabet.

**Comment by jxltom** [comment]
If so, does the storefront 1.0 also works correctly since user can also input latin or local alphat actually?

**Comment by fowczarek** [comment]
Yes, backend changes the local version to the raw version.

**Comment by maarcingebala** [comment]
@fowczarek Please update the changelog.

**Comment by fowczarek** [comment]
@maarcingebala 
Done

**Comment by fowczarek** [comment]
@maarcingebala Done

**Pull request merged**
