### PR TITLE
Waiting fulfillments return

### PR DESCRIPTION
**Pull request by tomaszszymanski129**
I want to merge this change because it adds support for returning waiting fulfillments.

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-4162 Refund option - fulfillments should change status from 'waiting for approval' to Refunded](https://app.clickup.com/t/2549495/SALEOR-4162)

**Review by maarcingebala — APPROVED** [review]

**Review by korycins — APPROVED** [review]
It look ok but keep in mind (and prepare a task) for refactoring this part of code. We should have a logic for refund/return in one place

**Comment by maarcingebala** [comment]
Status update - this PR is waiting for the corresponding dashboard changes; after we add them PR will be tested by QA.

**Comment by tomaszszymanski129** [comment]
Closing in favour of https://github.com/mirumee/saleor/pull/8062 which already contains it.

**Pull request closed without merging**
