### PR TITLE
Update links to point to new docs location

### PR DESCRIPTION
**Pull request by rafalp**
This PR updates our Readme and docs index to point people towards new documentation URL.

### CODE REVIEW

**Comment by patrys** [comment]
Shouldn't we remove the rest of `/docs/`?

**Comment by django-queries** [comment]
Here is the report for 4d5829cf567db819e17cbba8b77138b02b2e2515 (mirumee/saleor @ moved-docs)
Base comparison is 57423534ab3d5af854157e443fc21a2e1ea004ec.



<details><summary>No differences were found. (click me)</summary>
<p>

```diff
# api.benchmark checkout
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  add billing address to checkout     	         34	         34	             20
  add shipping to checkout            	          7	          7	              0
  checkout payment charge             	         14	         14	              0
  complete checkout                   	          6	          6	              0
  create checkout                     	         48	         48	             24

# api.benchmark homepage
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  retrieve main menu                  	          5	          5	              0
  retrieve product list               	          4	          4	              0
  retrieve secondary menu             	          5	          5	              0
  retrieve shop                       	          2	          2	              0

# api.benchmark product
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  product details                     	         13	         13	              3

# api.benchmark variant
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  retrieve variant list               	          9	          9	              2
```

</p>
</details>

**Comment by rafalp** [comment]
@patrys fixed, I've also updated the PR template to don't include documentation part.

**Comment by maarcingebala** [comment]
I wanted to wait with merging this, but OK 😄

**Comment by rafalp** [comment]
@maarcingebala sorry about that one, I've done that by force of habit 😅😂

**Pull request merged**
