### PR TITLE
Added integration support of Jaeger

### PR DESCRIPTION
**Pull request by NyanKiyoshi**
Jaeger will be enabled when passing `JAEGER_AGENT_HOST`.

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] Database migration files are up to date.
1. [x] The changes are tested.
1. [ ] GraphQL schema and type definitions are up to date.
1. [x] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by django-queries** [comment]
Here is the report for 7d3b8af9201a7a8335a68b00ace3f01d9b14b1d6 (NyanKiyoshi/saleor @ integration/add-jaeger)
Base comparison is 9833ef4fc068ee315ae5bbe8ef919435e0a1b138.



<details><summary>No differences were found. (click me)</summary>
<p>

```diff
# api.benchmark checkout
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  add billing address to checkout            	         34	         34	             20
  add shipping to checkout                   	          7	          7	              0
  checkout payment charge                    	         10	         10	              0
  complete checkout                          	          8	          8	              0
  create checkout                            	          5	          5	              1

# api.benchmark homepage
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  retrieve main menu                         	          5	          5	              0
  retrieve product list                      	          4	          4	              0
  retrieve secondary menu                    	          5	          5	              0
  retrieve shop                              	          2	          2	              0

# api.benchmark product
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  product details                            	         17	         17	              3
  retrieve product attributes                	          9	          9	              0

# api.benchmark variant
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  product variant bulk create                	         51	         51	              3
  retrieve variant list                      	         23	         23	              9

# api product sorting attributes
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  sort product not having attribute data     	         21	         21	              0
```

</p>
</details>

**Comment by patrys** [comment]
Once this lands we should open a ticket to add missing docs.

**Comment by Yahyaali1** [comment]
Is this integration actually working ? I am unable to any traces for backend service.

**Comment by patrys** [comment]
Yes, you can find an example setup in `saleor-platform`.

**Comment by Yahyaali1** [comment]
Thanks for the reply. That does not working. I have already tried using it. I see logs on the api but no services show up on the jager UI.

**Pull request merged**
