### PR TITLE
Fix send password reset mail with celery

### PR DESCRIPTION
**Pull request by primal100**
I want to merge this change because...

Sending the password reset mail asyncronously with celery fails, due to "User object not JSON serializable" error. This pull request removes the user object from context before providing it to the delay method, as the user is not needed. This allows the arguments to be serialized to JSON.

(If your changes affect the UI, providing "before" and "after" screenshots will
greatly reduce the amount of work needed to review your work.)

### Pull Request Checklist

(Please keep this section. It will make maintainer's life easier.)

1. [ x] Privileged views and APIs are guarded by proper permission checks.
1. [ x] All visible strings are translated with proper context.
1. [ x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ x] Database queries are optimized and the number of queries is constant.
1. [x ] The changes are tested.
1. [ x] The code is documented (docstrings, project documentation).
1. [x ] Python code quality checks pass: `pycodestyle`, `pydocstyle`, `pylint`.
1. [ x] JavaScript code quality checks pass: `eslint`.

### CODE REVIEW

**Comment by elwoodxblues** [comment]
@akjanik Could you take a look at this problem? I think the error may happen as a result of changes that you were working on recently. Removing the user instance from context seems more like a workaround than a solution.

**Comment by akjanik** [comment]
@elwoodxblues Sure.
I think that specific key of `context` should not be removed. It is being used by `send_templated_mail` and is mandatory argument.
Looking at example from django-templated-email:
https://github.com/vintasoftware/django-templated-email#sending-templated-emails
and oure email templates `source/account/password_reset`, I think it could be better to replace this particular key with user email, e.g.:
```
context['user'] = str(context['user'])
# OR
context['user'] = context['user'].get_full_name()
```
@mad-anne @elwoodxblues What do you think?

**Comment by NyanKiyoshi** [comment]
I don't have saleor under my eyes right now... But from what I remember, maybe we could refactor to `    user.send_password_reset_email()`?

**Comment by elwoodxblues** [comment]
I've just tested sending password reset on my local (master) and everything worked fine. How can I reproduce it? @akjanik Can you confirm this error?

**Comment by patrys** [comment]
Are you testing with eager mode on? Could it be that Celery does not serialize arguments when in eager mode (as it does not need to store them)?

**Comment by primal100** [comment]
Sorry yes, it's only when CELERY_ALWAYS_EAGER is False (so when CELERY_BROKER_URL is set to a Redis instance). Otherwise the request is not run asynchronously and so the arguments don't need to be serialized.

The error happens when the application attempts to add the request to the task queue:

image

@akjanik I don't think the user key is mandatory in context. If you look at the example you linked to, they include 'username', 'full_name' and 'signup_date' keys in the context, but not a 'user' key. For the templates they are using they needed those values, but none of them are mandatory. It's all dependent on what context the templates need.

The e-mail is delivered ok after removing the user key:

image

I thought about replacing the user object with something else, but looking over the Saleor password reset templates I couldn't find any reference to the user object in the templates, so I don't think it's needed. We could still include the extra context in case other users want to override the template. What do you think?

**Comment by primal100** [comment]
It could also be argued that maybe the password reset e-mail shouldn't be sent asynchronously at all. I think of using task queues for anything that isn't essential to the request at hand (order confirmation e-mails, google analytics, etc). 

But given password reset is the primary reason for the request and the user is re-directed to a page saying "We have sent you an e-mail. ", perhaps Saleor should send always send it synchronously and thus ensure the e-mail was sent before returning a response. In that case we would not need to worry about JSON serialization of the arguments.

**Comment by elwoodxblues** [comment]
Sending emails is a blocking operation which is the reason for using Celery. We shouldn't make any exceptions here.

I've eventually managed to reproduce the error with Celery enabled (eager mode off). It seems that Django uses the `user` instance in the original [password reset template](https://github.com/django/django/blob/master/django/contrib/admin/templates/registration/password_reset_email.html). Since we're overriding it completely, I think we could remove the user from the context as @primal100 proposed, but I think we should add an inline comment explaining why we're doing this.

**Pull request merged**
