### PR TITLE
Handle user_email resolver with an empty string

### LINKED ISSUE #2849: Creating empty order draft causes API to explode
### What I'm trying to achieve
To get order draft details from API.

### Steps to reproduce the problem
Execute this query
```
{
  orders {
    edges {
      node {
        id
        userEmail
      }
    }
  }
}
```

### What I expected to happen
Definitely not to throw an error.

### PR DESCRIPTION
**Pull request by Pacu2**
As the field was nonnullable, we could not return a null value for it in the API 

close #2849 

### Pull Request Checklist

1. [x] Privileged views and APIs are guarded by proper permission checks.
1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Database queries are optimized and the number of queries is constant.
1. [x] The changes are tested.
1. [x] The code is documented (docstrings, project documentation).
1. [x] GraphQL schema and type definitions are up to date.

### CODE REVIEW

**Comment by Pacu2** [comment]
@akjanik I've forgotten to include `null=True` on the model

**Comment by patrys** [comment]
I think it's easier to redefine the field to not be required at API level.

**Comment by Pacu2** [comment]
@patrys There's a problem with the resolvers, if user_email is equal to the empty string, I think we should return a null instead, which is not possible at this moment due to the field being not nullable.

**Comment by patrys** [comment]
If we override the field to make it not required at GraphQL level then we can safely return null for empty strings.

**Comment by Pacu2** [comment]
@patrys Right, got it

**Pull request merged**
