### PR TITLE
Support latest django-graphql-jwt

### PR DESCRIPTION
**Pull request by jxltom**
For making PR not so radical, https://github.com/mirumee/saleor/pull/2430 locked django-graphql-jwt to lower than 0.1.13.

In [django-graphql-jwt 0.1.13](https://github.com/flavors/django-graphql-jwt/blob/master/CHANGES.rst#0113), ```GraphQLJWTError``` is renamed to ```JSONWebTokenError``` and it does not provide backward compatibility.

Since it actually doesn't break compatibility with saleor and to have new features and fewer bugs, let's support the latest version and lock it to ```>=0.1.13```

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] GraphQL schema and type definitions are up to date.

### CODE REVIEW

**Comment by patrys** [comment]
Not sure why but seemingly unrelated dependency hashes change in this PR.

**Comment by jxltom** [comment]
Because we didn't pin specific version in Pipfile. For example, we only pin ```Django = ">=1.11"```, so if there are any new releases such as ```2.1.12```, ```pipenv lock``` will upgrade these packages to the latest version only if they match the requirments in Pipfile.

It has same behaviour with ```pip-tools```.

It looks like there is no way to only upgrade only a specific package but leave others untouched, except you pin all packages with specifc version by ```==some_version```. But doing that will break the easiness of upgrading pacakges.

**Comment by patrys** [comment]
`pip-tools` allows you to upgrade specific dependencies, I kind of expected `pipenv` to do the same.

**Comment by jxltom** [comment]
Unfortunately, it is not supported yet https://github.com/pypa/pipenv/issues/966. 😢

**Pull request merged**
