### PR TITLE
Support temporary checkout

### LINKED ISSUE #5207: Support instant checkouts for "buy now"
### What I'm trying to achieve
I have a scenario where the storefront supports adding to cart and also a "buy now" option. Since there is no cart system in saleor, I have adapted to use the checkout as a cart. When using `checkoutCreate`, each user is limited to only one open checkout at a time. Meaning that a new checkout cannot be created for the "buy now" while the user has items in their cart.

### Describe a proposed solution
The current design does make sense for most common use cases, and is quite convenient for cart systems. But having the option to create an instant disposable checkout would be a big help.

### Other solutions I've tried and won't work
One possible hack I can use is to back up the user's existing checkout (cart) as metadata, freeing up the checkout to be used for the buy now. Once completed, the cart can be restored. This would have some pitfalls and drawbacks, but should be possible.

Edit:
Oh looks like there's a related issue #5116

### PR DESCRIPTION
**Pull request by gsoec**
Fix  #5207  #5116
For authenticated users, to create a temporary `Checkout`
```js
	const result = await this.$apollo.mutate({
		mutation: createCheckoutMutation,
		variables: {
			checkoutInput: {
				lines,
				email: "my-email@example.com",
				isTemporary: true,
			}
		},
	})
```

### Pull Request Checklist

1. [x] Privileged views and APIs are guarded by proper permission checks.
1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Database queries are optimized and the number of queries is constant.
1. [x] Database migration files are up to date.
1. [x] The changes are tested.
1. [x] GraphQL schema and type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by django-queries** [comment]
Here is the report for bf71dc843d52e6e9b27de474d19aed49ae8e16d2 (gsoec/saleor @ multi_checkouts)
Base comparison is 997dbb519053c52380f191cb1b47b4473468e17c.



<details><summary>No differences were found. (click me)</summary>
<p>

```diff
# api.benchmark checkout
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  add billing address to checkout            	         34	         34	             20
  add shipping to checkout                   	          7	          7	              0
  checkout payment charge                    	         10	         10	              0
  complete checkout                          	          8	          8	              0
  create checkout                            	          5	          5	              1

# api.benchmark homepage
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  retrieve main menu                         	          5	          5	              0
  retrieve product list                      	          4	          4	              0
  retrieve secondary menu                    	          5	          5	              0
  retrieve shop                              	          2	          2	              0

# api.benchmark product
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  product details                            	         18	         18	              4
  retrieve product attributes                	          9	          9	              0

# api.benchmark variant
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  product variant bulk create                	         51	         51	              3
  retrieve variant list                      	         23	         23	              9

# api product sorting attributes
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  sort product not having attribute data     	         21	         21	              0
```

</p>
</details>

**Comment by korycins** [comment]
Hi @gsoec 
Thanks for the PR. Could you add some description? 
It is hard to understand the use-case and how it should work.

**Comment by gsoec** [comment]
Hi @korycins 
Thanks for your reply. I forgot to add related issues.I edited the first comment and added related issues -#5207 and #5116. 
could you give me some guidance on what description i should add and where to put description?

**Comment by maarcingebala** [comment]
Thanks for opening the PR @gsoec. Introducing the "Buy Now" feature is not on our roadmap now, so I'll close this PR. It's definitely something worth looking into in the future, but that would have to be paired with our storefront's development. Anyway, changes in this PR can be a useful reference for anyone customizing the codebase on its own. Thank you for your effort and understanding!

**Pull request closed without merging**
