### PR TITLE
Improve documentation for Heroku app deployment

### PR DESCRIPTION
**Pull request by raybesiga**
I want to merge this change because I wish to include the step for adding the Heroku remote. And also setting the Heroku NodeJS and Python buildpacks. 

Only the start of my effort to improve Saleor documentation during Hacktoberfest. :)

### CODE REVIEW

**Comment by raybesiga** [comment]
@patrys @Pacu2 seen this? :)

**Comment by Pacu2** [comment]
@raybesiga Sorry for the waiting time! We were really busy with the 2.0 release, slowly catching up.

**Comment by patrys** [comment]
Thank you both for the pull request and for the patience ✨

**Comment by raybesiga** [comment]
Thanks, guys. So proud of you for Saleor 2.0! Just wondering, is it ready for use in Production or should I wait a couple of months before I use in production? Also, expect a lot more PRs from me as regards to documentation. Best regards.

**Comment by patrys** [comment]
The API should be production ready. There are some missing endpoints though and we may rename some things before declaring it set in stone but we're trying to do a better job at documenting schema changes between releases now that we're using semantic versioning.

For the PWA app it's currently more of a tech demo. There are major features missing like account management, order tracking etc. The ultimate goal is for you to be able to fork just the PWA client and use a stock release of the backend which should make upgrades easier.

**Comment by raybesiga** [comment]
Thanks for the clarification @patrys! I am about to deploy my new e-commerce marketplace but my code right now is pre-Saleor 2.0 I am a little worried about breaking changes so I guess I will keep it this way for a few months. Best regards.

**Pull request merged**
