### PR TITLE
Remove unused imports in saleor and tests

### PR DESCRIPTION
**Pull request by jxltom**
This PR removes the unused imports in saleor and tests directory

### Pull Request Checklist

1. [x] Privileged views and APIs are guarded by proper permission checks.
1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Database queries are optimized and the number of queries is constant.
1. [x] Database migration files are up to date.
1. [x] The changes are tested.
1. [x] The code is documented (docstrings, project documentation).
1. [x] GraphQL schema and type definitions are up to date.
1. [x] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by michaljelonek** [comment]
Looks good to me 👍 

I wonder though whether we want to include tests back in codeclimate. [This PR](https://github.com/mirumee/saleor/pull/1384) excluded them, so we're never assuring quality of code in our tests, but the question is.. should we? 

Also I just realised we never run isort on `__init__.py` files, as isort by default skips them. I think we might want to include those as well? 

cc: @maarcingebala

**Comment by jxltom** [comment]
It is weird that the tests failed...

**Comment by maarcingebala** [comment]
Tests are an integral part of the project so I think we could actually re-enable checking code style issues for them. I also agree about enabling `isort` for `__init__.py` files. [This comment](https://github.com/timothycrosley/isort/issues/139#issuecomment-451616157) explains how to do that. @jxltom Do you think you could do that in this PR so we'll have it all sorted out in one go?

**Comment by maarcingebala** [comment]
Tests that failed were using dates, maybe we have indeterministic tests? But I don't recall to have seen them failing before.

**Comment by jxltom** [comment]
@maarcingebala No problem, I will handle it. :D

**Comment by jxltom** [comment]
@maarcingebala @maciekjablonski This PR is ready to review. Besides enabling tests in codeclimate and ```__init__``` for isorts, I also update threhold of codeclimate: updating max argument to 5 which is same as pylint's default value and max lines to 1000 since it is quite common to have a lot of lines in single file in saleor.

**Comment by maarcingebala** [comment]
But only now I saw `codeclimate - 606 issues to fix` 🙂There are some issues about arguments and lines count, are you sure the config is good? What were the limits before this change?

**Comment by jxltom** [comment]
@maarcingebala The original config is codeclimate's defaults: 4 maximum arguments and 250 max lines. The new settings deduces the warnings but not gets rid of all of them. I can restore to original settings or make the threshold even larger if you prefer.

**Comment by michaljelonek** [comment]
@jxltom @maarcingebala 

A lot of those issues, while valid, make absolutely no sense to fix in tests. Those would explain why the tests were excluded in the first place. Looking at the code climate documentation it looks like there's no way to disable certain checks using exclude patters -> https://docs.codeclimate.com/docs/advanced-configuration#section-exclude-patterns. Only global or plugin (or engines in our case) exclusions are available, so we could disable for example pylint and duplication plugins (engines) and only have pep8 and isort run there. Additionally code climate by default excludes tests -> https://docs.codeclimate.com/docs/default-analysis-configuration, perhaps it's not the best tool to assure quality in tests.

But I don't want more time and this PR in its original form wasted, so what I propose is to exclude tests how they were, just merge what we have here without the `codeclimate.yml` change. We would ignore most of those issues anyway, so kinda beats the point of checking for them. We could definitely come back to this topic in a separate issue (I did not expect it would bring that many issues to be fair).

Thoughts?

**Comment by maarcingebala** [comment]
I fully agree with @michaljelonek on this, let's revert the codeclimate config changes.

**Comment by jxltom** [comment]
@maarcingebala @michaljelonek I've reverted the changes in codeclimate configurations.

**Comment by maarcingebala** [comment]
@jxltom Thanks! We also agreed that we want to keep the tests excluded as it was before. Could you revert the `.codeclimate.yml` file?

**Comment by jxltom** [comment]
@maarcingebala No problem, done.

**Comment by maarcingebala** [comment]
Thanks!

**Pull request merged**
