### PR TITLE
Add google cloud missing config

### PR DESCRIPTION
**Pull request by marcelocbf**
I want to merge this change because Google Cloud is missing a few configuration options present on AWS storage config. Basically the ability to return non-signed urls and use a custom endpoint for media stored in GCS

* Part or all of this configuration needed django-storages 1.11 version. Following the recommendation on the "Contributing" page, I updated pyproject.toml for future use of poetry but also manually requirements_dev.txt since pyproject.toml seemed outdated
* I also followed the pattern used in core.storages.AWSMediaStorage of setting the custom_endpoint from the media custom endpoint manually for probably a future use for status hosting as well
* I can also create a pull request for the documentation update if this PR gets accepted

P.S: This is my first contribution to an open source project, so let me know if I should be doing something else or there is something missing or wrong here that I need to address

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [X] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Review by maarcingebala — APPROVED** [review]

**Comment by maarcingebala** [comment]
Thanks for opening the PR @marcelocbf. Can you please also update `django-storages` version in `requirements.txt`?

**Comment by unicast** [comment]
I was about to submit a similar PR because of the missing `GS_DEFAULT_ACL`, thank you for creating this one!

**Comment by marcelocbf** [comment]
> Thanks for opening the PR @marcelocbf. Can you please also update `django-storages` version in `requirements.txt`?

Done! I will check the docs and update it as well

**Comment by maarcingebala** [comment]
@marcelocbf Congrats on your first open-source PR, and especially, a PR in Saleor 🎉  👍

**Comment by marcelocbf** [comment]
> @marcelocbf Congrats on your first open-source PR, and especially, a PR in Saleor 🎉 👍

Awesome, thanks! 😃

**Comment by unicast** [comment]
@maarcingebala any chance we could get this one backported to 2.11?

**Pull request merged**
