### PR TITLE
Stock allocation

### PR DESCRIPTION
**Pull request by patrys**
Important changes:

* stock is now marked as allocated when the order is created
* stock is deallocated and decreased when a delivery group is shipped
* as the current models require one order line to use one stock record, I have changed max allowed quantity for purchase to reflect max quantity held by a single stock record (we can extend this in future to create multiple order lines for the same product to split it between multiple locations)

### CODE REVIEW

**Comment by mociepka** [comment]
What about cart allocation @patrys ? As fare I remember we agree to inform user about quantity changes in cart view and checkout steps.

**Comment by patrys** [comment]
This is out of scope of this change. There is no difference between someone allocating stock and admin changing the stock quantity.

**Comment by mociepka** [comment]
In [this line](https://github.com/mirumee/saleor/pull/471/files#diff-b97412023cc3cbb54a3eabd653b6d5c0R151) you change the product quantity, what will happen with user cart which contains more that that value?

**Comment by patrys** [comment]
I don't change quantity, I change quantity allocated to reflect new quantity. This is an existing order management form.

What happens to carts is not important in this pull request, from cart's perspective this is the same as going to the product management page and reducing the stock quantities.

**Comment by mociepka** [comment]
My bad, looks fine.

**Pull request merged**
