### PR TITLE
Add `customers` app

### PR DESCRIPTION
**Pull request by dominik-zeglen**
Quick preview:

zrzut ekranu 2018-06-07 o 16 29 41
zrzut ekranu 2018-06-07 o 16 30 01
zrzut ekranu 2018-06-07 o 16 30 20
zrzut ekranu 2018-06-07 o 16 30 12

### CODE REVIEW

**Comment by Pacu2** [comment]
Isn’t “price” label adjusted to the right, while all the others are aligned to the left?

Not sure if that’s intended or not.

**Comment by dominik-zeglen** [comment]
It is planned. Every numeric ( therefore comparable ) values should be aligned to the right, so should be its label. It is easier to read and compare values this way.

**Comment by mirekm** [comment]
Including `#` @dominik-zeglen? ;)

**Comment by dominik-zeglen** [comment]
Okay, numeric and comparable :)

**Pull request merged**
