### PR TITLE
Set python version in docker from 3.6 to 3.7

### PR DESCRIPTION
**Pull request by bykof**
I want to merge this change because...

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] Database migration files are up to date.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] GraphQL schema and type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by hairychris** [comment]
I think you also need to change the COPY commands here: https://github.com/mirumee/saleor/blob/40134010c18c320778410b3cfdba03b05480148c/Dockerfile#L55

**Comment by bykof** [comment]
@hairychris done.
Whats about the Pipfile? Currently there is selected python version == 3.6
Change to python 3.7?

**Comment by hairychris** [comment]
I would suspect so, hopefully someone else can confirm, I don't see what harm it would do.

**Comment by bykof** [comment]
Hm... I think everyone has to build the pipenv new... because it will say that your env is in 3.6 and the specified version is 3.7

**Comment by hairychris** [comment]
That's a valid point, it's a bit annoying at the moment if you only have Python 3.7 installed (e.g. if you did 'brew install python3') so at some point I guess we have to bite the bullet.

**Comment by jxltom** [comment]
Changing to 3.7 in Pipfile will make the pipenv re-locking all dependencies under python37. We need to make sure all the deps are supporting python37, if we are going to do that.

The deployment in heroku requires installing packages in Pipfile but the python version is pinned in ```runtime.txt``` as python36. If we change to python37 in Pipfile, it is better to also change that since there may be problems if we are running python36 but installing packages which are locked under python37.

Maybe python36 is more stable than python37 for production server purpose? If so, I would recommend not changing to python37 in Pipfile.

**Comment by maarcingebala** [comment]
Thanks for a valuable input @jxltom. I'm using 3.7 with Saleor on regular basis, but we would have to update `Pipfile` and `runtime.txt` and test again if Saleor builds and runs properly and if the Heroku build works as well after those changes.

**Comment by jxltom** [comment]
Yes, exactly 👍

**Comment by akjanik** [comment]
I would like to support this PR.
After long time, while building with `docker-compose build` I had issues with celery:
```
Get:1 http://security.debian.org jessie/updates InRelease [44.9 kB]
Ign http://deb.debian.org jessie InRelease
Ign http://deb.debian.org jessie-updates InRelease
Get:2 http://deb.debian.org jessie Release.gpg [2420 B]
Ign http://deb.debian.org jessie-updates Release.gpg
Get:3 http://deb.debian.org jessie Release [148 kB]
Get:4 http://security.debian.org jessie/updates/main amd64 Packages [825 kB]
Ign http://deb.debian.org jessie-updates Release
Get:5 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages

Err http://deb.debian.org jessie-updates/main amd64 Packages
  404  Not Found
Fetched 10.1 MB in 7s (1441 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'celery' failed to build: The command '/bin/sh -c apt-get -y update   && apt-get install -y gettext   && apt-get clean   && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```
Changig `3.6` -> `3.7` solved this.
See also
https://github.com/celery/celery/pull/5403
cc @maarcingebala

**Comment by maarcingebala** [comment]
Heroku supports now Python 3.7.2. So we should bump Python version to 3.7 in `Dockerfile`, `runtime.txt`, `Pipfile` and generate new `Pipfile.lock`. Then we should test Heroku deployment and if all of that works, we'll be able to merge this PR. @akjanik Could you take care of that?

**Pull request merged**
