### PR TITLE
Products export unsupported operation fix

### PR DESCRIPTION
**Pull request by tomaszszymanski129**
I want to merge this change because it fixes broken CSV export when using S3 as storage.

Tested locally both with local storage and S3.

Removed broken tests for now, they have to be rerwitten and so will be done in subsequent PR.

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by tomaszszymanski129** [comment]
@IKarbowiak The file is being deleted after the function ends as it closes automatically and is being deleted (as default behavior of `NamedTemporaryFile`) but you're right, it's better to explictily close it. As for tests i plan to re-write them shortly so that doesn't really matter if we remove them here.

**Comment by IKarbowiak** [comment]
In my opinion is, if somebody else will be working on fixing the tests, it will be easier to refactor existing one, that writing new ones from the beginning or looking for old ones in history.

**Comment by IKarbowiak** [comment]
Looks good 👍, but did you test it on the big sample like 50 000 and 100 000 products?

**Comment by tomaszszymanski129** [comment]
@IKarbowiak tested with local storage and S3 with over 100k products in database. Resulting file is about 5mb, takes some time but works flawlessly (and of course uploads without any problems to S3).

**Pull request merged**
