### PR TITLE
Make TIME_ZONE and LANGUAGE_CODE configurable via env vars

### PR DESCRIPTION
**Pull request by maersu**
I want to merge this change because...

In order to make the settings more configurable, I would like to merge the following changes:

* TIME_ZONE and LANGUAGE_CODE are configurable via env vars
* Faker uses the specified language code so the dummy data are more accurate to the developers location

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by patrys** [comment]
Hi, `TIME_ZONE` is not meant to be changed. The API is supposed to only operate in UTC. The clients are expected to convert to the correct time zone for display/input. I know this currently affects time ranges that rely on dates alone, we're going to fix that by converting the relevant date inputs to date/time inputs.

**Comment by maersu** [comment]
@patrys thanks! 

Just for my curiosity: Why can the API just operate with UTC?

**Comment by patrys** [comment]
Given a UTC timestamp, you can accurately represent that point in time in any given time zone. The opposite is not true because of daylight saving times (an entire hour is duplicated whenever the clocks are shifted back).

**Comment by maarcingebala** [comment]
What about LANGUAGE_CODE, do we want to set it with env variable @patrys?

**Comment by patrys** [comment]
Not sure what it's used for, is it just a fallback language? If so, I think the Dashboard is a better place for it.

**Comment by maarcingebala** [comment]
It's one of Django's standard configuration options: https://docs.djangoproject.com/en/3.1/ref/settings/#language-code.

**Comment by maarcingebala** [comment]
We use it only for email translations as there are no other templates in Saleor now.

**Comment by patrys** [comment]
Aren't emails translated based on the user's language? I know we record the language each order was placed in, not sure about signup and password reset but the user's preferred language should also be used there.

**Comment by incorvia** [comment]
> Hi, the `TIME_ZONE` is not meant to be changed. The API is supposed to only operate in UTC. The clients are expected to convert to the correct time zone for display/input. I know this currently affects time ranges that rely on dates alone, we're going to fix that by converting the relevant date inputs to date/time inputs.

When Saleor's team plans to 'fix that by converting the relevant date inputs.. ' is the intention to then provide a configuration within the Dashboard to present everything in a configurable time zone?

**Comment by patrys** [comment]
Yes, the dashboard will let you pick a timezone when entering a date/time (but the value will be stored as UTC in the backend).

**Pull request closed without merging**
