### PR TITLE
[WIP] Add pypy3.5 to the test matrix

### PR DESCRIPTION
**Pull request by patrys**
This adds pypy3.5 to the test matrix.

Important changes:
* `psycopg2cffi` instead of `psycopg2`; very fast under PyPy but does not come with wheel packages for Windows

### CODE REVIEW

**Comment by patrys** [comment]
Something is not right with either `pytest` or `coverage`:

```
490 passed, 4 warnings in 1018.09 seconds
                          ^^^^^^^
```

**Comment by patrys** [comment]
I'm going to pause this until we can figure out why tests are twice as slow under pypy3.5. I suspect coverage but it's supposed to be fast these days.

**Comment by NyanKiyoshi** [comment]
After looking up on the Internet, it looks like it's a common issue for PyPy to run many many times slower than CPython on `coverage.py`.

From my tests, in use, PyPy3 makes almost no differences on saleor. Overall PyPy3 was only 1.25 seconds slower than Python3.6.4. (I tested really quickly, I only made it run on the index page with 10k requests with 10 concurrent requests)

[I tried to disable it on my fork](https://github.com/NyanKiyoshi/saleor/commit/d9cacb7012e8686f4fc33ff37cbb5eb1e41b5a30), instead of taking 20+ minutes, it now takes around 8 minutes... (was around 6 minutes each time in my two week older branch, probably because of `npm build-emails` or something. I'm not sure) Still way slower than Python3 on pytest.

With coverage: https://travis-ci.org/NyanKiyoshi/saleor/builds/337124914
Without coverage: https://travis-ci.org/NyanKiyoshi/saleor/builds/337124914

I'm not sure of what we can really do about this.

**Comment by patrys** [comment]
Interesting. Maybe we should only run coverage on one interpreter or even one interpreter + one Django version?

**Comment by NyanKiyoshi** [comment]
Probably, yes, it won't make a real difference for the coverage if we don't run it on every environment

**Comment by maarcingebala** [comment]
Closing this PR due to no activity.

**Pull request closed without merging**
