### PR TITLE
Fix/userprofile

### LINKED ISSUE #666: Improve profile page
Profile page should have 3 sections in tabs:
* Orders
* Account & Password
* Addresses

Orders section should be the default one.
Also we should discuss if address management is really required in separated view on profile page.

### PR DESCRIPTION
**Pull request by weronka**
Closes #666

### CODE REVIEW

**Comment by artursmet** [comment]
image


image

**Comment by patrys** [comment]
Are you guys sure I should be assigned to this? It looks like a whole lot of commits I know nothing about 😉 .

**Comment by artursmet** [comment]
@weronka Could you rebase it with demo-store?

**Comment by weronka** [comment]
@artursmet done

**Pull request merged**
