### PR TITLE
Adjust minimum validators on CartLine, OrderLine and FulfillmentLine

### LINKED ISSUE #2912: It should not be possible to create a line with 0 quantity
At this moment one can create `CartLine` / `OrderLine` / `FulfillmentLine` with 0 `quantity`
We should adjust a validator on the models to prevent such actions, as it doesn't make sense to have an item with no quantity assigned.

### PR DESCRIPTION
**Pull request by the-bionic**
I want to merge this change because...
close #2912

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] GraphQL schema and type definitions are up to date.

### CODE REVIEW

**Comment by Pacu2** [comment]
I think you need to include migrations for those changes.

**Comment by the-bionic** [comment]
Yeah, that's right.

**Comment by the-bionic** [comment]
I'll do that right away.

**Comment by the-bionic** [comment]
How about dropping the ```MaxValueValidator``` on ```quantity_fulfilled``` as well?

**Comment by Pacu2** [comment]
Thank you for picking this up!

**Comment by the-bionic** [comment]
Glad to be of assistance.

**Pull request merged**
