### PR TITLE
Disable style loader in dev mode

### LINKED ISSUE #3720: Style loader can not load css properly
In this commit https://github.com/mirumee/saleor/commit/d9f00cea27cac52b80314ca910a2e80d7692e12c, the ```style-loader``` is used for dev mode, however I found it can not load css properly when using webpack without production mode.

saleor e commerce

### PR DESCRIPTION
**Pull request by jxltom**
Fixes #3720

### Pull Request Checklist

1. [x] Privileged views and APIs are guarded by proper permission checks.
1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Database queries are optimized and the number of queries is constant.
1. [x] Database migration files are up to date.
1. [x] The changes are tested.
1. [x] The code is documented (docstrings, project documentation).
1. [x] GraphQL schema and type definitions are up to date.
1. [x] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by maarcingebala** [comment]
@piotrgrundas This is the change that you've made recently. Could you comment on that? Is the issue that @jxltom reported valid?

**Comment by piotrgrundas** [comment]
Well - it allows u to have source maps for sass which is very helpful for styling. The downside is that it introduces some glitch while loading the page caused probably by the fact that normally css is served by django.

I would not call this an issue since it helps a bit of local development and does not affect production builds.

**Comment by jxltom** [comment]
Probably it works well for dashboard 2.0, but at least for storefront 1.0 in local development, the layout is wrong. It looks like the browser will report wrong source map error as I found in my chrome console.

**Comment by piotrgrundas** [comment]
I've added it as I was fixing the old storefront, and I'm checking it now and it shows sources correctly.

**Comment by jxltom** [comment]
@piotrgrundas Am i doing anything wrong for local dev? I first run ```npm start``` and then running ```python manage.py runserver```. Are you sure you delete all the cached assets in your system and not running ```webpack``` with production mode?

**Comment by jxltom** [comment]
This is terrible for me. :P
black hoodie saleor e commerce

**Comment by piotrgrundas** [comment]
Well, did not see that coming. Let's merge it.
I see that `updateProductImageHeight` is messing up probably because styles aren't injected immediately like before. When I have some time I'll try to fix it.

**Comment by jxltom** [comment]
Thanks, that worths some investigation.

**Pull request merged**
