### PR TITLE
Add verbose message to color field

### PR DESCRIPTION
**Pull request by mitcom**
Add verbose error message to hexidecimal color field. Now there is only _Enter a valid value._ with label _Color_. Nothing to tell user use format like `#cf0369` or `#0f9`

### CODE REVIEW

**Comment by bogdal** [comment]
Maybe we should add an example:
`Value must be in hexadecimal notation (e.g. #ababab)`

**Comment by car3oon** [comment]
How about using some simple color picker: http://labs.abeautifulsite.net/jquery-minicolors/ ? Check "Hidden input" example, in this case user won't have to worry at all about valid color hex value.

**Comment by patrys** [comment]
I'm with @bogdal here, “hexadecimal” without examples is just asking the user to visit Wikipedia.

**Comment by mitcom** [comment]
I did like @bogdal said, but I think the message is too long and looks weird if is breaken

**Comment by artursmet** [comment]
What is current status of this pull request? @mitcom @patrys ?

**Comment by patrys** [comment]
We need better UI. A color picker would be nice so people don't have to guess what format to use.

**Pull request closed without merging**
