### PR TITLE
Return more than one page of search results

### LINKED ISSUE #1160: Search results page always contains only one page
https://demo.getsaleor.com/search/?q=jo returns only one page but there are actually more results. We've found that it's caused by `results = list(results)` at https://github.com/mirumee/saleor/blob/master/saleor/search/views.py#L29. If you remove this line then search works correctly.

### PR DESCRIPTION
**Pull request by akhavr**
Fixes #1160 in the original repository

### CODE REVIEW

**Comment by elwoodxblues** [comment]
@akhavr Thanks for your contribution! I'm afraid that the real problem is that Elasticsearch has it's own pagination mechanism (which is by default 10 results), which our pagination doesn't take into account. Also the function `paginate_results` expects list argument as a first argument; after your change `results` will be a generator which I think won't work correctly. We'll be working on adding custom pagination that works with Elasticsearch.

**Comment by jardev** [comment]
@elwoodxblues yes, it will be a generator and it works for us fairly well - https://hotguns.info/search/?q=%D1%81%D0%B0%D0%B9%D0%B3%D0%B0

**Comment by elwoodxblues** [comment]
@jardev Which version of Python and Django are you using? On Python 3.5.3, Django 1.11 and latest Saleor (master) I get the following error:

```
Traceback:

File "/Users/marcin/.pyenv/versions/saleor/lib/python3.5/site-packages/django/core/paginator.py" in count
  79.             return self.object_list.count()

During handling of the above exception ('generator' object has no attribute 'count'), another exception occurred:

File "/Users/marcin/.pyenv/versions/saleor/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/Users/marcin/.pyenv/versions/saleor/lib/python3.5/site-packages/django/core/handlers/base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "/Users/marcin/.pyenv/versions/saleor/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/Users/marcin/.pyenv/versions/saleor/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/marcin/mirumee/saleor/saleor/search/views.py" in search
  34.     page = paginate_results(results, request.GET, settings.PAGINATE_BY)

File "/Users/marcin/mirumee/saleor/saleor/search/views.py" in paginate_results
  15.         page = paginator.page(page_number)

File "/Users/marcin/.pyenv/versions/saleor/lib/python3.5/site-packages/django/core/paginator.py" in page
  57.         number = self.validate_number(number)

File "/Users/marcin/.pyenv/versions/saleor/lib/python3.5/site-packages/django/core/paginator.py" in validate_number
  46.         if number > self.num_pages:

File "/Users/marcin/.pyenv/versions/saleor/lib/python3.5/site-packages/django/utils/functional.py" in __get__
  35.         res = instance.__dict__[self.name] = self.func(instance)

File "/Users/marcin/.pyenv/versions/saleor/lib/python3.5/site-packages/django/core/paginator.py" in num_pages
  91.         if self.count == 0 and not self.allow_empty_first_page:

File "/Users/marcin/.pyenv/versions/saleor/lib/python3.5/site-packages/django/utils/functional.py" in __get__
  35.         res = instance.__dict__[self.name] = self.func(instance)

File "/Users/marcin/.pyenv/versions/saleor/lib/python3.5/site-packages/django/core/paginator.py" in count
  84.             return len(self.object_list)

Exception Type: TypeError at /search/
Exception Value: object of type 'generator' has no len()
```

**Comment by jardev** [comment]
elwoodxblues got it. We use Python 2.

**Comment by elwoodxblues** [comment]
For this reason I cannot merge it. We want to support Python 2.7, 3.4 and 3.5. Anyway, thanks for your effort and trying to help us with Saleor! We'll fix this bug in different PR that will add support for pagination in Elasticsearch.

**Pull request closed without merging**
