### PR TITLE
Move shipping data to order

### LINKED ISSUE #201: Get rid of address book aliases
We do our best to always show the full address, there is little merit in forcing the user to come up with a unique alias.

### LINKED ISSUE #266: Move shipping address and delivery method to order
We currently allow each delivery group to be shipped elsewhere and using other means. This is a corner case and results in checkout being hard to customize.

### PR DESCRIPTION
**Pull request by patrys**
Both shipping address and shipping method are now features of the order itself. This makes it possible to customize the checkout flow to contain both addresses on the same screen and makes it easier to send order data to fraud screening services.

Fixes #266 
Fixes #201

### CODE REVIEW

**Comment by patrys** [comment]
@mociepka care to take a look as well?

**Comment by mociepka** [comment]
Code looks good, but now we end up with only standard shipping method. What if we want to sell ebooks or ebooks and normal books in one store? Now we are forcing user to fill all shipping data even baskets with digital content only.

**Comment by patrys** [comment]
We now have support for shippable and non-shippable groups. Shipping step is only added when necessary.

**Comment by patrys** [comment]
@mociepka care to review?

**Pull request merged**
