### PR TITLE
copying address for order

### PR DESCRIPTION
**Pull request by pcompassion**
just an idea, not tested..

### CODE REVIEW

**Comment by patrys** [comment]
What does it do? A few lines above there is a call to `_save_address` which already creates a copy.

**Comment by pcompassion** [comment]
Are you sure it does create a copy?

_save_address calls

User.objects.store_address()

and it calls
Address.objects.store_address()

and it calls
Address.objects.get_or_create()

this is create not `copy`

user.default_shipping_address
and order.shipping_address
is pointing to the same Address model

and when user changes his default_shipping_address

Order's shipping_address is affected.




2016-03-10 16:58 GMT+09:00 Patryk Zawadzki <notifications@github.com>:

**Comment by patrys** [comment]
Hmm, it should create a second address object not assigned to a user, if it doesn't then it's a regression we should fix. No need to introduce a new address type.

**Comment by pcompassion** [comment]
I haven't tested, but it looks like a bug.

when user's first address is stored, I see only one `get_or_create` call
and it means there's only one Address instance.

and user has foreign key (default_shipping_address)
and order has foreign key (shipping_address)

both to Address model.

Sorry if I confused you with my limited knowledge, but I don't see it being
copied anywhere.



2016-03-10 17:06 GMT+09:00 Patryk Zawadzki <notifications@github.com>:

**Comment by patrys** [comment]
No no, thanks for your work, we'll get it fixed. :+1: I think this regression appeared during the last checkout overhaul. That should teach us to write more integration tests.

**Comment by pcompassion** [comment]
glad to help. such a nice project!

fyi, I'm using the version prior to the last checkout overhaul, and I think it had the same problem.

**Comment by patrys** [comment]
This should be fixed with the latest pull request.

**Pull request closed without merging**
