### PR TITLE
Add better styles for password reset procedure

### LINKED ISSUE #782: Improve styles in password recovery forms
Styles should be fixed to fit rest of project

### PR DESCRIPTION
**Pull request by artursmet**
Closes #782 

image

image

image

### CODE REVIEW

**Comment by mirekm** [comment]
Why are those inputs so long?

**Comment by mirekm** [comment]
It both looks bad and doesn't work well from the UX point of view.

**Comment by artursmet** [comment]
@mirekm Here is the design:

image

Probably it needs more work on the details in front-end part.

**Comment by patrys** [comment]
It has the same elements as the design but they look nothing alike 😄 We need someone from the front-end team to fix this.

**Pull request merged**
