### PR TITLE
Remove host mounted volume in docker-compose

### PR DESCRIPTION
**Pull request by tiangolo**
Remove host mounted volume in docker-compose as the app expects files created at build time that doesn't exist in the mounted source files.

Even though I like the development trick of mounting the source code during development to be able to "hot reload" instead of having to build the image from scratch again, it doesn't work in this case, because it expects some files and directories to exists.

It expects:

* a directory `/app/static` , [created at build time](https://github.com/mirumee/saleor/blob/master/Dockerfile#L64)
* a directory `/app/media`, [created at build time](https://github.com/mirumee/saleor/blob/master/Dockerfile#L64)

As I wanted to develop locally with the mounted app directory, I tried creating them by hand, but the files are created and owned by my own Linux user, with `uid` `1000`, and the Linux user created inside the container is a new user (`saleor`), and as it is created as a system user, it has `uid` `999`, so it cannot create anything inside those directories.

I tried [commenting out the lines to create a custom user inside the container instead of the default `root` user](https://github.com/mirumee/saleor/blob/master/Dockerfile#L63).

But then I discovered that it also expects:

* A file `/app/webpack-bundle.json` [copied from the previous Docker build stage, created at build time](https://github.com/mirumee/saleor/blob/master/Dockerfile#L54)

...and probably some other files in subsequent steps.

## I want to merge this change because...

With the current layout of the source files and architecture, it's not feasible to mount the local app directory for development. If it is wanted / required, while a new layout is defined, this would simplify testing Saleor locally with Docker.

## Relevant issues

Directly causes: #3049
I can't say that it causes #2642 , but after adding the directories manually, it causes the problems described in these subsequent comments: https://github.com/mirumee/saleor/issues/2642#issuecomment-414584455 https://github.com/mirumee/saleor/issues/2642#issuecomment-419433915 
https://github.com/mirumee/saleor/issues/2642#issuecomment-427600603

Then, after adding the directories manually and removing the custom user or having any other workaround, it causes: #2506

### Pull Request Checklist

1. [n/a] Privileged views and APIs are guarded by proper permission checks.
1. [n/a] All visible strings are translated with proper context.
1. [n/a] All data-formatting is locale-aware (dates, numbers, and so on).
1. [n/a] Database queries are optimized and the number of queries is constant.
1. [x] The changes are tested.
1. [n/a] The code is documented (docstrings, project documentation).
1. [n/a] GraphQL schema and type definitions are up to date.

### CODE REVIEW

**Comment by patrys** [comment]
I agree that we should drop this, we should also move the static assets outside of the saleor directory and then re-evaluate which parts should be shadowed by local directories and which should not.

**Comment by artursmet** [comment]
I agree @patrys, but maybe we could merge this one first and then work on moing assets outside of saleor directory?

**Comment by patrys** [comment]
Yes, they should be separate changes.

**Comment by ajostergaard** [comment]
Would it make sense to include removing ", will automatically reload code" from https://saleor.readthedocs.io/en/latest/customization/docker.html as part of this change.

**Comment by tiangolo** [comment]
Good point @ajostergaard :+1: . 

I just updated it.

**Comment by tiangolo** [comment]
:tada:

**Pull request merged**
