### PR TITLE
Remove quantity-allocated generation in populatedb script

### PR DESCRIPTION
**Pull request by MartinSeibert**
I removed the quantity-allocated value generation from the create_variant function in the random_data.py data generation script.

Ref #2572

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] GraphQL schema and type definitions are up to date.

### CODE REVIEW

**Comment by Pacu2** [comment]
Hi @MartinSeibert, thank you for this contribution, do you mind using [closing keywords](https://help.github.com/articles/closing-issues-using-keywords/)? It makes the maintainer life easier.

**Comment by maarcingebala** [comment]
@MartinSeibert We could try to implement this change according to what @patrys suggested. Would you have some time to work on that?

**Comment by MartinSeibert** [comment]
Yeah I'll move forward with @patrys strategy. I'll post in that thread if I need any clarification, I'm still familiarizing myself with the project.

**Comment by maarcingebala** [comment]
As this issue is quite irritating, I'd merge that simple change and keep the original issue to fix it when we have time.

**Comment by maarcingebala** [comment]
Thanks for your contribution @MartinSeibert. Feel free to continue working on improving this solution as discussed in issue #2572 when you have time!

**Pull request merged**
