### PR TITLE
Setup celery logging

### PR DESCRIPTION
**Pull request by tomaszszymanski129**
I want to merge this change because it sets up logging of celery so we can reference particular async task by ID / name of task.

when task succeeds and contains logging:
```
{"asctime": "2021-05-07T10:56:46Z", "levelname": "INFO", "celeryTaskId": "bfc58e8f-35b2-42c2-b015-33fb164a1f9f", "celeryTaskName": "saleor.product.thumbnails.create_product_thumbnails", "message": "Creating thumbnails for 120", "hostname": "linuz"} 

{"asctime": "2021-05-07T10:56:46Z", "levelname": "INFO", "celeryTaskId": "bfc58e8f-35b2-42c2-b015-33fb164a1f9f", "celeryTaskName": "saleor.product.thumbnails.create_product_thumbnails", "message": "Created 6 thumbnails", "hostname": "linuz"} 

{"asctime": "2021-05-07T10:56:46Z", "levelname": "INFO", "celeryTaskId": "bfc58e8f-35b2-42c2-b015-33fb164a1f9f", "celeryTaskName": "saleor.product.thumbnails.create_product_thumbnails", "celeryTaskRuntime": 0.12916755300102523, "hostname": "linuz"}
```

So we see logs entry sharing same celeryTaskId, first two contains messages, last one even contains celeryTaskRuntime so we can easily know how long it took

In case task fails during execution we see:

```
{"asctime": "2021-05-07T11:00:22Z", "levelname": "ERROR", "celeryTaskId": "12d1a7e3-f7bf-43ba-91d2-e73a1a7de7d1", "celeryTaskName": "saleor.product.thumbnails.create_product_thumbnails", "exc_info": "Here we see the traceback", "hostname": "linuz"}
```

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [X] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [x] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-2855 Have JSON logging in Celery](https://app.clickup.com/t/2549495/SALEOR-2855)

**Review by IKarbowiak — APPROVED** [review]

**Review by fowczarek — APPROVED** [review]

**Review by NyanKiyoshi — CHANGES_REQUESTED** [review]
Not everything is logged in JSON:
```
[2021-04-29 10:29:28,444: INFO/MainProcess] Received task: saleor.foo[taskID]
[2021-04-29 10:29:48,556: INFO/ForkPoolWorker-1] Creating thumbnails for  1
```

**Comment by tomaszszymanski129** [comment]
@NyanKiyoshi please re-review, now logging in tasks also formats correctly, i've put example on description.

**Comment by patrys** [comment]
Task linked: [SALEOR-3518 Error on saving long pages](https://app.clickup.com/t/2549495/SALEOR-3518)

**Comment by tomaszszymanski129** [comment]
Seems to be all working now.
Messages like "Received task: ...id" should no longer appear - however updated environment is necessary - we've bumped celery from 5.0.5 to 5.1.0 and that solved it.
There are two loggers defined for `celery.app.trace` that handles celery internal logs and `celery.task` defined for task logging.
Tasks have to use task_logger instead of logger to log things properly, couldn't really find more generic solution (and this approach is stated in celery docs).

**Comment by NyanKiyoshi** [comment]
Will be testing the change on Thursday or Friday

**Review by NyanKiyoshi — APPROVED** [review]

**Pull request merged**
