### PR TITLE
Update MUI and take some care of Storybook

### PR DESCRIPTION
**Pull request by dominik-zeglen**
I want to merge this change because it adds new inputs and improves storybook a bit.

### Screenshots
Screenshot 2019-05-15 at 15 09 41
Screenshot 2019-05-15 at 15 09 52
Screenshot 2019-05-15 at 15 10 05

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] Database migration files are up to date.
1. [x] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] GraphQL schema and type definitions are up to date.
1. [x] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by piotrgrundas** [comment]
image
image

**Comment by dominik-zeglen** [comment]
Oh cmon it's mostly snapshots!

**Comment by piotrgrundas** [comment]
It doesn't really mater what it is. U know that equally I can just approve it because of amount of changes....

**Comment by dominik-zeglen** [comment]
There's like 500 LOC that really do need to be read. The rest are snapshots and one-line changes like 
`variant="headline"` -> `variant="h5"`.

**Pull request merged**
