### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by dominik-zeglen**
I want to merge this change because it improves UI a little bit. Like, a really little bit.

- increased minimum table cell height
- increased minimum card title height
- switched table header font weight to regular
- replaced useless product type selection in product details with label
- improved typography in customer history, sale summary, and voucher summary components

Before:
Screenshot 2019-04-16 at 11 32 07
After:
Screenshot 2019-04-16 at 11 30 14

Before:
Screenshot 2019-04-16 at 11 31 41
After:
Screenshot 2019-04-16 at 11 30 48

Before:
Screenshot 2019-04-16 at 11 31 29
After:
Screenshot 2019-04-16 at 11 30 58

Before:
Screenshot 2019-04-16 at 11 31 57
After:
Screenshot 2019-04-16 at 11 30 29

Before:
Screenshot 2019-04-16 at 11 31 50
After:
Screenshot 2019-04-16 at 11 30 38

Before:
Screenshot 2019-04-16 at 11 38 13
After:
Screenshot 2019-04-16 at 11 29 38

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] Database migration files are up to date.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] GraphQL schema and type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by patrys** [comment]
Please include before/after screenshots when asking for a review.

**Comment by mirekm** [comment]
A brief description or some bullet points mentioning of what the improvement is would also help.

**Comment by patrys** [comment]
@dominik-zeglen I think some before/after are switched around?

**Comment by dominik-zeglen** [comment]
My bad

**Pull request merged**
