### PR TITLE
Increase size of Payment and Transaction tokens 

### PR DESCRIPTION
**Pull request by bufke**
To accommodate payment gateways with longer tokens. Such as Authorize.net which can be as large
as length 216. This is the result of discussing with @patrys and maciek

# Impact

* [X] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Review by korycins — APPROVED** [review]

**Comment by korycins** [comment]
@maarcingebala When we will merge it, we need to cherry-pick it to the master also.

**Review by maarcingebala — APPROVED** [review]

**Comment by maarcingebala** [comment]
It seems that [Black failed in CI](https://travis-ci.com/github/mirumee/saleor/jobs/428055042), @bufke can you run `black` on the migration file that you added?

**Comment by bufke** [comment]
Done @maarcingebala

**Review by maarcingebala — APPROVED** [review]

**Comment by maarcingebala** [comment]
All good now.

**Pull request merged**
