### PR TITLE
Minor preorder changes

### PR DESCRIPTION
**Pull request by Kwaidan00**
I want to merge this change because it contains minor changes for preorder feature:
- webhook payload update
- product export update
- `populatedb` script update

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-2998 Preorders](https://app.clickup.com/t/2549495/SALEOR-2998)

**Comment by patrys** [comment]
Task linked: [SALEOR-3807 12. Update populatedb](https://app.clickup.com/t/2549495/SALEOR-3807)

**Comment by patrys** [comment]
Task linked: [SALEOR-3805 10. Update webhook payloads](https://app.clickup.com/t/2549495/SALEOR-3805)

**Comment by patrys** [comment]
Task linked: [SALEOR-3806 11. Update product export](https://app.clickup.com/t/2549495/SALEOR-3806)

**Review by fowczarek — APPROVED** [review]

**Review by maarcingebala — APPROVED** [review]

**Pull request merged**
