### PR TITLE
Replaced `float: right` on category filter labels by a flexbox

### PR DESCRIPTION
**Pull request by NyanKiyoshi**
After a lot of "fun" recovering those changes from the hypervisor that had a critical failure... I want to merge this change because... It improves the visual rendering of the frontstore. :smile: 

When the filter name is too long, it makes the filter label's arrow ugly on the frontstore.

To explain the changes, here is two screenshots.

### Pull Request Checklist

(Please keep this section. It will make maintainer's life easier.)

1. [x] Privileged views and APIs are guarded by proper permission checks.
1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Database queries are optimized and the number of queries is constant.
1. [x] The changes are tested.
1. [x] The code is documented (docstrings, project documentation).
1. [x] Python code quality checks pass: `pycodestyle`, `pydocstyle`, `pylint`.
1. [x] JavaScript code quality checks pass: `eslint`.

### CODE REVIEW

**Comment by NyanKiyoshi** [comment]
@dominik-zeglen my current solution would be to break the words by wrapping.



Another way would also be to add a `text-overflow: hidden`

```css
text-overflow: ellipsis;
overflow: hidden;
```

.

**Comment by dominik-zeglen** [comment]
I'd fix HTML anyway; by doing this we can evade future problems. Please let us know if you want to fix it by yourself, or should I do it.

**Comment by NyanKiyoshi** [comment]
I will let you handle this.

I also saw that today:


But I guess Saleor would need a lot of cleaning. It will probably be slowly improved over time.

**Comment by elwoodxblues** [comment]
@dominik-zeglen What's the status of this PR? I'd rather take one step at a time. If this PR fixes styling issues, let's merge it (if the code is all right). If there are other things to fix, either we do it now or we open an issue.

**Comment by dominik-zeglen** [comment]
@elwoodxblues I'll do it today.

**Comment by dominik-zeglen** [comment]
Hello @NyanKiyoshi, we merged yesterday some fixes regarding storefront filters, so you may want to check it out how we did it. Thank you very much for your contribution to Saleor.

**Pull request closed without merging**
