### PR TITLE
Add support for filter descriptions and deprecations

### LINKED ISSUE #4398: Add description and deprecation support to filters
`FilterInputObjectType` doesn't provide a way to document fields. We could add two fields to the meta-class: `descriptions = {field: description}` and `deprecations = {field: reason}`.

### PR DESCRIPTION
**Pull request by michizhou**
Added support for descriptions and deprecations to filters with new meta class fields.

Closes #4398 

### Pull Request Checklist

1. [x] Privileged views and APIs are guarded by proper permission checks.
1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Database queries are optimized and the number of queries is constant.
1. [x] Database migration files are up to date.
1. [x] The changes are tested.
1. [x] GraphQL schema and type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by django-queries** [comment]
Here is the report for bcf3b26de9740345ac3e98d4cc1b6e2e1dcb35fd (michizhou/saleor @ add-filter-support)
Base comparison is 5d8eb35ab2ba3532303ac63dd65dccde9111b3f9.



<details><summary>No differences were found. (click me)</summary>
<p>

```diff
# api.benchmark checkout
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  add billing address to checkout            	         34	         34	             20
  add shipping to checkout                   	          7	          7	              0
  checkout payment charge                    	         14	         14	              0
  complete checkout                          	          6	          6	              0
  create checkout                            	         48	         48	             24

# api.benchmark homepage
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  retrieve main menu                         	          5	          5	              0
  retrieve product list                      	          4	          4	              0
  retrieve secondary menu                    	          5	          5	              0
  retrieve shop                              	          2	          2	              0

# api.benchmark product
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  product details                            	         15	         15	              3
  retrieve product attributes                	         13	         13	              2

# api.benchmark variant
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  product variant bulk create                	         51	         51	              3
  retrieve variant list                      	         15	         15	              6

# api product sorting attributes
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  sort product not having attribute data     	         21	         21	              0
```

</p>
</details>

**Comment by maarcingebala** [comment]
Hey, thanks for opening the PR. Actually the issue description in #4398 is a bit mistaken about adding support for deprecation messages for filter arguments - that's [not supported in GraphQL yet](https://github.com/graphql/graphql-spec/pull/525). 

But we can add support for descriptions. Actually I'm looking at your code and it doesn't solve the issue yet. We should be able to do: 

```
class ProductFilterInput(FilterInputObjectType):
    class Meta:
        descriptions = {"is_published": "Filter products by publication status."}
        filterset_class = ProductFilter
```

So we would need to implement attaching those descriptions to fields inside the `FilterInputObjectType` initialization.

**Comment by michizhou** [comment]
@maarcingebala Are you suggesting that all I have to do is implement a way to link my existing code with the `Meta` class by adding `descriptions` as a new attribute inside `FilterInputObjectType`? Or do I have to also rewrite/refactor my existing code as well? I would appreciate it if you could let me know so I know what to expect moving forward.

**Comment by maarcingebala** [comment]
I looked into this a bit more and it's interesting, as it seems we actually support filter descriptions based on filter labels: https://github.com/mirumee/saleor/blob/be4d85a18fe4397b39c4deb471850c39c1c31ea4/saleor/graphql/core/types/filter_input.py#L61

It's not really used but we we'll handle adding those descriptions. One thing that I would change is to use `help_text` instead of `label`, since `label` is usually short, while `help_text` is more often used for descriptions. What I mean is to change the line I linked to above to something like that:

```
field_type.description = getattr(filter_field, "help_text", "")
```

**Comment by maarcingebala** [comment]
@michizhou If you want you can take care of changing that line to use `help_text` and test if it works for you. If not let me know, I'll handle this change.

**Comment by michizhou** [comment]
@maarcingebala I have modified the specified line responsible for retrieving the filter descriptions such that it now does so using the filter `help_text` attribute as per your suggestion. Please let me know if this change will suffice. Otherwise, I'd be happy to make additional changes if need be.

**Comment by maarcingebala** [comment]
Looks good now! I think this is ready to merge and in a separate PR we will need to add descriptions to all filters to make the API better documented.

**Comment by michizhou** [comment]
@maarcingebala Just to confirm, will this PR count toward Hacktoberfest?

**Comment by maarcingebala** [comment]
Since it was opened during Hacktoberfest and it fixes an issue that was marked with this label, yes we will count it 🎉.  Please send me your shipping address and preferred socks size (40-43 or 44-46 / EU sizes) at marcin@mirumee.com.

**Pull request merged**
