### PR TITLE
Enables opentracing parent calling saleor

### PR DESCRIPTION
**Pull request by benoj**
I want to merge this change because...

At present saleor assumes that it is the initial request from the UI layer and creates a new jaeger/opentracing span even if a parent span is provided in the HTTP headers.

This PR allows upstream services to pass a opentracing headers in the request and have full tracing across services.

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by benoj** [comment]
I'm not sure what is happening with the GH action `NyanKiyoshi/pytest-django-queries-ci-tools@v1` - this change shouldn't affect the queries in any way. I'm guessing this is an issue unrelated to this change, but because it's touching the endpoint it is being highlight? 

Am I interpreting this correctly?

**Comment by maarcingebala** [comment]
@NyanKiyoshi Can you take a look at this?

> I'm not sure what is happening with the GH action NyanKiyoshi/pytest-django-queries-ci-tools@v1 - this change shouldn't affect the queries in any way. I'm guessing this is an issue unrelated to this change, but because it's touching the endpoint it is being highlight?

**Comment by NyanKiyoshi** [comment]
It is looking for repository name to post a comment but looks at the wrong place: the fork. Thus it tries to post a comment to the pull request at Mirumee/saleor-fork (where `saleor-fork` is the source of the pull request).

It is fine to ignore, I will fix it whenever I am available for it.

**Review by patrys — APPROVED** [review]

**Review by fowczarek — APPROVED** [review]

**Comment by maarcingebala** [comment]
Thank you for contributing to Saleor @benoj 🎉

**Pull request merged**
