### PR TITLE
Add spanish locale

### PR DESCRIPTION
**Pull request by mativs**
Hi, used to work work with saleor and I have to add spanish locale. This are my files. The translation isn't perfect, but I think it will be usefull for others to use it as a base translation po file instead of working from scratch.

Hope it helps.

### CODE REVIEW

**Comment by patrys** [comment]
Would you mind uploading it to Transifex instead? This way others have a simple way to improve the translation and you get to keep credit for the parts that you did.

**Comment by mativs** [comment]
@patrys no problem at all, do you have a link or guide me were I must upload them?

**Comment by mativs** [comment]
https://www.transifex.com/mirumee/saleor-1/ this one?

**Comment by patrys** [comment]
Yes, that's the one, sorry for the delay.

**Comment by mativs** [comment]
All done!! Hope it helps, and remember that I'm not a translator so surely you will find errors.

**Comment by israelzuniga** [comment]
@mativs Matias: In parallel I started translating (before seeing this PR), but I'm glad to see that you pulled almost all the translation strings.

I was checking that sometime there are capital letters at the second word (Variante Borrada vs Deleted variant). Would you mind if I edit those strings at Transifex?

**Comment by mativs** [comment]
@israelzuniga obviously there is no problem at all!!! I'm sure you will find some mistakes, so go on.

**Comment by cdvv7788** [comment]
@patrys I updated some translations too. To update the code is there anything else we need to do on our side?

**Comment by patrys** [comment]
I'm closing this as there are no more actionable items here. Thank you everyone for contributing! ✨ 

All translations are now merged from Transifex into the codebase on a weekly basis.

**Pull request closed without merging**
