### PR TITLE
Fix stripe

### LINKED ISSUE #5799: Stripe - A token may not be passed in as a PaymentMethod. Instead, use payment_method_data with type=card and card[token]
### What I'm trying to achieve
Complete a checkout with Stripe as the payment method.

### Steps to reproduce the problem
1. Add keys to Stripe plugin
2. Retrieve token via StripeJS/Elements
3. Mutation createCheckoutPayment(...)
4. Mutation completeCheckout(...)

### What I expected to happen
Checkout to be completed, instead it throws an error

### Screenshots
image

**System information**
Operating system:
MacOS Cataline 10.15.5
Running Saleor with Docker

### PR DESCRIPTION
**Pull request by LeOndaz**
Fixed #5799

### CODE REVIEW

**Comment by LeOndaz** [comment]
MB I forgot to commit the changes lol, anyway it's fixed now

**Comment by LeOndaz** [comment]
I think I missed up the PR ~.~

**Comment by LeOndaz** [comment]
@korycins what do you think? (I've tested and it's working, payments are accepted)

**Comment by korycins** [comment]
@LeOndaz Can you share the stripe docs related to this change? I am trying to find something, but without any success :c
@maarcingebala  You're already working on the improvement of the stripe gateway. What do you think about these changes?

**Comment by maarcingebala** [comment]
I couldn't reproduce the issue described in #6800, I tested Stripe recently and payments were created successfully in Stripe.

**Comment by LeOndaz** [comment]
@korycins I don't know about the documentation part (I found nothing), I found this as a result of the error telling me I'm passing the token as payment method data, something like the image in the issue mentioned above, and I just edited the code to match what the error logs said, I got payments working with this 

image of successful payments

@maarcingebala Can you try with the latest version of both saleor & dashbaord? (the master branch), I'm using both and I update regularly, I'm neither using the storefront nor saleor sdk though, I'm sending all the data as expected (paymentData is not there in stripe, a token from stripe.createToken(...), checkoutId, no amount (uses checkout total))

**Comment by LeOndaz** [comment]
@korycins @maarcingebala I think I'm getting my head wrapped around the issue (not sure), It's expected that a string token should be entered in `checkoutPaymentCreate`, however, if you pass a string, you get an error saying you can't use a string as a payment_method, instead use payment_method_data, I saw [this spectrum thread](https://spectrum.chat/saleor/development/issue-with-stripe-gateway-a-token-may-not-be-passed-in-as-a-paymentmethod-instead-use-payment-method-data-with-type-card-and-card-token-tok-1hpunhlf9gdrjvxqcqbxggbe~f100b0f4-e63f-4312-8fda-56befb11d303), so basically the token is being used as a payment method on the backend which should not happen, so the solution imo is either the token in createPayment should be paymentData: JSONString and we pass a full payment_method created by `stripe.createPaymentMethod()` and this will change the interface of usage so it's is a breaking change, or we can change it to payment_method_data and specify the token directly here and this is not a breaking change as the interface of usage will be the same and this is describing this PR, there's also a `Token.create` in stripe's python package

**Comment by LeOndaz** [comment]
@korycins @maarcingebala Furthur more, the process_payment in stripe calls authorize with some `PaymentData`, the `PaymentData.token` is a string, but stripe expects `payment_method` not to be a string

**Comment by LeOndaz** [comment]
@korycins any news?

**Comment by korycins** [comment]
@LeOndaz Hey, just letting you know -  I am working on a new implementation of the Stripe payment gateway, which will use a custom payment flow described [here](https://stripe.com/docs/payments/integration-builder). It should be included in 3.0

**Comment by LeOndaz** [comment]
Thank you, I'll be following, or maybe contributing

**Comment by korycins** [comment]
I should open the PR in a couple of days (hope so 😄  )

**Comment by korycins** [comment]
I beleive we can close this PR. New stripe plugin is placed here - https://github.com/mirumee/saleor/pull/7452 , docs are here - https://github.com/mirumee/saleor-docs/pull/277

**Pull request closed without merging**
