### PR TITLE
Single page category search

### LINKED ISSUE #674: GraphQL Category page improvements
- [x] Drop product count from categories tree
- [x] Add sorting
- [x] Better styles for category tree
- [x] Include discounts in product price (requires changes in API and rebasing category page branch with latest master)

### PR DESCRIPTION
**Pull request by elwoodxblues**
This PR adds the dynamic category page that uses React and Relay to fetch and filter products.
Fixes #674

### CODE REVIEW

**Comment by elwoodxblues** [comment]
@benekex2 There are two things we have to improve in sidebar filters:
image
- now it is possible to collapse the whole checkbox group, but we should hide only unchecked filters
- the whole filter header should be clickable, not only the arrow on the right

**Comment by artursmet** [comment]
@elwoodxblues Could you rebase or merge with demo-store once again?

**Comment by artursmet** [comment]
As we discussed, we'll firstly merge demo-store branch into master and then this branch to master. This will avoid potential merge conflicts

**Comment by elwoodxblues** [comment]
@benekex2 I've updated this branch to the latest master. There is some problem with bootstrap grid in product list, also something is broken in price range filter. Could you fix it?

image

**Pull request merged**
