### PR TITLE
description_plaintext blocks are improperly concatenated

### PR DESCRIPTION
**Pull request by daltonsena**
Signed-off-by: Dalton <daltonsena@users.noreply.github.com>

fix issue #7599 

Thanks guys for the wonderful work!!! Saleor is a great project and I learn a lot from him.

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by maarcingebala** [comment]
@daltonsena Good catch! I checked the example from the issue locally and can confirm the bug. Would you mind fixing the test `test_clean_editor_js_for_list` that is now failing after your changes?

**Review by patrys — COMMENTED** [review]
Wouldn't it be more efficient to add the results to a list and then `" ".join(...)` it?

**Comment by daltonsena** [comment]
@patrys I agree! Can I make the change?

**Comment by daltonsena** [comment]
> @daltonsena Good catch! I checked the example from the issue locally and can confirm the bug. Would you mind fixing the test `test_clean_editor_js_for_list` that is now failing after your changes?

@maarcingebala I had forgotten about the tests, sorry. I took the chance and changed the behaviour to a list/join.

**Comment by daltonsena** [comment]
> Wouldn't it be more efficient to add the results to a list and then `" ".join(...)` it?

@patrys I agree!

**Comment by daltonsena** [comment]
@patrys Hi! I made three new modifications in this PR.

1. Added a new case test for editorjs named "test_clean_editor_js_for_complex_description" that will check a description with two paragraphs and two list elements
2. Changed the variable which was called "string" to "plain_text_list"
3. Now we use a list (plain_text_list var) to add the results and then " ".join(...) it as a return of the method (as you suggested)

**Review by maarcingebala — APPROVED** [review]

**Review by IKarbowiak — APPROVED** [review]

**Review by patrys — APPROVED** [review]

**Review by tomaszszymanski129 — APPROVED** [review]

**Pull request merged**
