### PR TITLE
Improve contextual markers and translations for python code

### PR DESCRIPTION
**Pull request by itbabu**
Hello,

First PR for #182 related to python files.

I've not yet generated any migration yet.
I might have done some typos since the number of strings involved.

### CODE REVIEW

**Comment by patrys** [comment]
Outstanding work!

**Comment by patrys** [comment]
@itbabu We've added Saleor to Transifex and would love if you could share at least a partial translation. Let me know if you're open to join us there.

**Comment by itbabu** [comment]
@patrys It's ok for me, I'll start to share my translations soon.

**Comment by patrys** [comment]
This is awesome! Thank you!

**Pull request merged**
