### PR TITLE
Remove hashes from requirements files

### LINKED ISSUE #5045: ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==
Is OK to develop/install saleor with Python3.8 on Mac? It seemed that I cannot,  ` importlib-resources; python_version < "3.7"`

### What I'm trying to achieve
to install locally on mac
### Steps to reproduce the problem
1.  pip install -r requirements_dev.txt

### What I expected to happen
no errors

### Screenshots

error:
```
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    importlib-resources; python_version < "3.7" from https://files.pythonhosted.org/packages/2f/f7/b4aa02cdd3ee7ebba375969d77c00826aa15c5db84247d23c89522dccbfa/importlib_resources-1.0.2-py2.py3-none-any.whl#sha256=6e2783b2538bd5a14678284a3962b0660c715e5a0f10243fd5e00a4b5974f50b (from pre-commit==1.20.0->-r requirements_dev.txt (line 521))
(
```

**System information**
Operating system:  Mac OS
Browser: None

### LINKED ISSUE #5070: Unable to deploy saleor on heroku trough deploy button.
### What I'm trying to achieve
Deploy on the heroku server

### Steps to reproduce the problem
1. Click on the deploy button

### What I expected to happen
Deployment

### Screenshots

Screen Shot 2019-12-15 at 1 15 37 PM
Screen Shot 2019-12-15 at 1 15 32 PM

**System information**
Operating system: Heroku
Browser: Chrome

### PR DESCRIPTION
**Pull request by IKarbowiak**
I want to merge this change to remove hashes from requirements files. Probably because of hashes there is problem with heroku deployment.

Closes #5045;
Closes #5070.

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] Database migration files are up to date.
1. [x] The changes are tested.
1. [ ] GraphQL schema and type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by django-queries** [comment]
Here is the report for e94a4aa5132e17e6580f9ab6af3cf74b75689c9e (mirumee/saleor @ remove-hashes-from-requirements)
Base comparison is b0a0a04b4e0ab228f354b7d0b8b9023dfa096787.



<details><summary>No differences were found. (click me)</summary>
<p>

```diff
# api.benchmark checkout
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  add billing address to checkout            	         34	         34	             20
  add shipping to checkout                   	          7	          7	              0
  checkout payment charge                    	         10	         10	              0
  complete checkout                          	          8	          8	              0
  create checkout                            	         50	         50	             24

# api.benchmark homepage
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  retrieve main menu                         	          5	          5	              0
  retrieve product list                      	          4	          4	              0
  retrieve secondary menu                    	          5	          5	              0
  retrieve shop                              	          2	          2	              0

# api.benchmark product
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  product details                            	         15	         15	              3
  retrieve product attributes                	          9	          9	              0

# api.benchmark variant
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  product variant bulk create                	         51	         51	              3
  retrieve variant list                      	         15	         15	              6

# api product sorting attributes
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  sort product not having attribute data     	         21	         21	              0
```

</p>
</details>

**Comment by tboulogne** [comment]
Hello,

Same problem here, anyway to solde this please ?

Regards

```
Collecting importlib-metadata>=0.18; python_version < "3.8"
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    importlib-metadata>=0.18; python_version < "3.8" from https://files.pythonhosted.org/packages/e9/71/1a1e0ed0981bb6a67bce55a210f168126b7ebd2065958673797ea66489ca/importlib_metadata-1.3.0-py2.py3-none-any.whl#sha256=d95141fbfa7ef2ec65cfd945e2af7e5a6ddbd7c8d9a25e66ff3be8e3daf9f60f (from kombu==4.6.7->-r requirements.txt (line 210))
```

**Comment by aselam** [comment]
> 
> 
> Hello,
> 
> Same problem here, anyway to solde this please ?
> 
> Regards
> 
> ```
> Collecting importlib-metadata>=0.18; python_version < "3.8"
> ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
>     importlib-metadata>=0.18; python_version < "3.8" from https://files.pythonhosted.org/packages/e9/71/1a1e0ed0981bb6a67bce55a210f168126b7ebd2065958673797ea66489ca/importlib_metadata-1.3.0-py2.py3-none-any.whl#sha256=d95141fbfa7ef2ec65cfd945e2af7e5a6ddbd7c8d9a25e66ff3be8e3daf9f60f (from kombu==4.6.7->-r requirements.txt (line 210))
> ```

Hello,

Replace requirements.txt with the one in the pull request : https://github.com/mirumee/saleor/blob/e94a4aa5132e17e6580f9ab6af3cf74b75689c9e/requirements.txt

I tried it yesterday and it worked perfectly.

**Comment by tboulogne** [comment]
Hello @aselam ,

Thanks for tips.
I just update to python 3.8 and it works without any changes.

Regards

**Comment by chetabahana** [comment]
I use to [manage](https://docs.getsaleor.com/docs/advanced/managing-dependencies/) the requirements files with hashes and build in [Docker Hub](https://hub.docker.com/repository/docker/chetabahana/saleor/builds) without problems:

```
$ poetry export -f requirements.txt -o requirements.txt
$ poetry export -f requirements.txt -o requirements_dev.txt --dev
```

I noticed that since [PR#5160](https://github.com/mirumee/saleor/pull/5160) this line on `requirements_dev.txt` :
```
pycparser==2.19 \
    --hash=sha256:a988718abfad80b6b157acce7bf130a30876d27603738ac39f140993246b25b3
```
[was changed](https://github.com/chetabahana/saleor/blob/1b9b02dc2a01481406a9cc27b149f27a67f33418/requirements_dev.txt#L590) to:
```
pycparser==2.19; sys_platform == "win32" and platform_python_implementation == "CPython" \
    --hash=sha256:a988718abfad80b6b157acce7bf130a30876d27603738ac39f140993246b25b3
```
which raise an [error](https://hub.docker.com/repository/registry-1.docker.io/chetabahana/saleor/builds/88a4c08c-cea3-44f2-870e-36073c0b5674):
```
Collecting pycparser
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==.
These do not:
pycparser from https://files.pythonhosted.org/packages/68/9e/49196946aee219aead1290e00d1e7fdeab8567783e83e1b9ab5585e6206a/pycparser-2.19.tar.gz#sha256=a988718abfad80b6b157acce7bf130a30876d27603738ac39f140993246b25b3
(from cffi==1.13.2->-r requirements_dev.txt (line 69))

Removing intermediate container d16e8a4e48f4
The command '/bin/sh -c pip install -r requirements_dev.txt' returned a non-zero code: 1
```
The build error was [solved](https://hub.docker.com/repository/registry-1.docker.io/chetabahana/saleor/builds/252a407b-6fa5-4d7c-b970-f6f5ea1d2da0) when I [manually changed](https://github.com/chetabahana/saleor/blob/b64f49bd110ad200d764278be313de9c1c0cb9ed/requirements_dev.txt#L590) the line back to:
```
pycparser==2.19 \
    --hash=sha256:a988718abfad80b6b157acce7bf130a30876d27603738ac39f140993246b25b3
```
So I assume that the package problem was not come from its hash but from its platform description.

**Comment by maarcingebala** [comment]
Thanks @chetabahana, we'll check it. We would rather want to have these hashes.

**Pull request merged**
