### PR TITLE
Form on product variant is now creating value if the attribute has no values

### LINKED ISSUE #1735: Entering an attribute value with characters in a variant product
If a variant product has an attribute without values associated to it and then, saleor decides to return a char field instead of a choice field. So if we enter an attribute value for this product variant, it makes saleor crash when opening the product on the storefront because it's thinking it's a pk.

Example:
1. A dummy attribute without values
dummy attribute without values

---

2. Then, a product variant where we define a non integer value (otherwise, saleor thinks it's a pk) 

```
Environment:


Request Method: GET
Request URL: http://0.0.0.0:4999/products/abant-4/

Django Version: 1.11.9
Python Version: 3.6.4
Installed Applications:
['storages',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sitemaps',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'django.contrib.auth',
 'django.contrib.postgres',
 'django.forms',
 'saleor.userprofile',
 'saleor.discount',
 'saleor.product',
 'saleor.cart',
 'saleor.checkout',
 'saleor.core',
 'saleor.graphql',
 'saleor.order.OrderAppConfig',
 'saleor.dashboard',
 'saleor.shipping',
 'saleor.search',
 'saleor.site',
 'saleor.data_feeds',
 'versatileimagefield',
 'django_babel',
 'bootstrap4',
 'django_fsm',
 'django_prices',
 'django_prices_openexchangerates',
 'graphene_django',
 'mptt',
 'payments',
 'webpack_loader',
 'social_django',
 'django_countries',
 'django_filters',
 'django_celery_results',
 'impersonate',
 'phonenumber_field']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django_babel.middleware.LocaleMiddleware',
 'saleor.core.middleware.discounts',
 'saleor.core.middleware.google_analytics',
 'saleor.core.middleware.country',
 'saleor.core.middleware.currency',
 'saleor.core.middleware.site',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'impersonate.middleware.ImpersonateMiddleware']



Traceback:

File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/home/sayuri/py3venv/lib/python3.6/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/sayuri/development/saleor_fork/saleor/product/views.py" in product_details
  62.         product, request.discounts, request.currency)

File "/home/sayuri/development/saleor_fork/saleor/product/utils.py" in get_variant_picker_data
  192.                 int(variant_value))

Exception Type: ValueError at /products/abant-4/
Exception Value: invalid literal for int() with base 10: 'str value for the attribute that has no values!'
```

### PR DESCRIPTION
**Pull request by NyanKiyoshi**
Form on product variant was accepting chars as attribute value but once we were trying to open the product page from the storefront, an exception occurred.

So, the edit is to still accept the str value but instead of storing it raw, we create the value instance and store the value pk.

But, for we still accept chars value if the attribute is in the base Product. (product form)
Since it won't raise any exception.

It fixes #1735.

### Pull Request Checklist

(Please keep this section. It will make maintainer's life easier.)

1. [x] Privileged views and APIs are guarded by proper permission checks.
1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Database queries are optimized and the number of queries is constant.
1. [x] The changes are tested.
1. [x] The code is documented (docstrings, project documentation).
1. [x] Python code quality checks pass: `pycodestyle`, `pydocstyle`, `pylint`.
1. [x] JavaScript code quality checks pass: `eslint`.

### CODE REVIEW

**Comment by elwoodxblues** [comment]
Hey @NyanKiyoshi, we've finally found some time to take a look at this problem. I was skeptical about automatically creating the attribute value objects, where the user wanted a simple string attribute value. But while it makes sense to have such attributes at the product level, I couldn't think of a real-life example for variants. That's why I think your solution is good. This will effectively allow for creating variant attributes with predefined values only.
When you have time, please fix the conflicting file and we'll merge it to master. Thanks!

**Comment by elwoodxblues** [comment]
That may be the real-life example that I was looking for. Then the problem is not the variant form in the dashboard, but the variant picker which fails to render such case.

**Comment by patrys** [comment]
To be fair I think it usually doesn't make sense to pick variants based on most free-form entry attributes. I think in the book case the only attribute you'd be interested in is the cover/binding type. Everything else (dimensions, number of pages, year of publication, ...) including any other selectable attributes should just be merged into the product details table placed below the description.

It looks like we should be able to select which attributes to show in the picker. If the selected options are not enough to narrow variants down a single SKU, display an additional variant selection field like we do for products with no variant attributes.

How does Shopify handle this UX-wise?

**Comment by elwoodxblues** [comment]
They use only free-form text attributes and generated choices in the storefront similarly to how we do it. I think we should only fix the variant picker to not throw errors and try to access choice values for attributes that don't have them predefined and just render the free-text choices.

**Comment by elwoodxblues** [comment]
After a closer investigation with @akjanik, we discovered that our variant picker doesn't actually support the free-text attributes at all, as it only takes into account attributes with `AttributeChoiceValue` objects associated. I think we should treat all attributes equally and start creating value objects always.

**Comment by elwoodxblues** [comment]
Moved to #1964.

**Pull request closed without merging**
