### PR TITLE
Bump requirements

### PR DESCRIPTION
**Pull request by fowczarek**
Bump requirements

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by fowczarek** [comment]
Blocked, We should generate a new `cassette` for adyen.

**Comment by maarcingebala** [comment]
We can update all requirements except for Adyen and open a task to bump Adyen later.

**Comment by fowczarek** [comment]
But the main goal of this task is to update Adyen because the old version not working correctly.

**Comment by maarcingebala** [comment]
OK 👍

**Pull request closed without merging**
