### PR TITLE
optimize images

### PR DESCRIPTION
**Pull request by Julian-B90**
I want to merge this change because i optimized some images

### CODE REVIEW

**Comment by django-queries** [comment]
Here is the report for 1fef77855e36d7bb02f9aca86e5a414fedde5c58 (Julian-B90/saleor @ feature/optimize-some-images)
Base comparison is 6cf784392ebfbdf219baaeb2d636b6e1e3860fb2.



<details><summary>No differences were found. (click me)</summary>
<p>

```diff
# api.benchmark checkout
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  add billing address to checkout            	         34	         34	             20
  add shipping to checkout                   	          7	          7	              0
  checkout payment charge                    	         14	         14	              0
  complete checkout                          	          6	          6	              0
  create checkout                            	         48	         48	             24

# api.benchmark homepage
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  retrieve main menu                         	          5	          5	              0
  retrieve product list                      	          4	          4	              0
  retrieve secondary menu                    	          5	          5	              0
  retrieve shop                              	          2	          2	              0

# api.benchmark product
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  product details                            	         15	         15	              3
  retrieve product attributes                	         13	         13	              2

# api.benchmark variant
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  retrieve variant list                      	         18	         18	              8

# api product sorting attributes
  test name                                  	left count 	right count	duplicate count
  -------------------------------------------	-----------	-----------	---------------
  sort product not having attribute data     	         21	         21	              0
```

</p>
</details>

**Comment by maarcingebala** [comment]
Thanks for opening a PR! What kind of optimization did you apply to those images? I'm comparing them and don't see any artifacts so I think the optimization is fine. Have you checked if thumbnails are rendered properly when using optimized images? For example, with the images we have now, I'm getting such artifacts in the old storefront on the product list:

image

While on the product details page this images looks rather fine:

image

I'm only wondering if this optimization won't make it worse for the thumbnails.

**Comment by Julian-B90** [comment]
I have use https://kraken.io. I will check all the images again.

**Comment by maarcingebala** [comment]
Closing due to no activity.

**Pull request closed without merging**
