### PR TITLE
Add category details to dashboard views

### LINKED ISSUE #1372: Change category details view in the dashboard
The category details page should be consistent with the rest of the details pages that we have (e.g. product). Changes to be introduced:
- [x] Add a card with the category details and links to edit or remove the category
- [x] Add a list of subcategories below the details card with the "Add" button
- [x] Move form to edit the category from modal to static view

### PR DESCRIPTION
**Pull request by koradon**
Add category detail card to dashboard/category/list.html.
Rename detail.html to form.html.
Delete dashboard/category/modal/edit.html.

I want to merge this change because...
This PR adds similar design of Categories to the one from other views with lists.
This PR fixes #1372 

screenshot from 2017-12-05 15-33-50
screenshot from 2017-12-05 15-33-56
screenshot from 2017-12-05 15-34-01
screenshot from 2017-12-05 15-34-06
screenshot from 2017-12-05 15-34-13
screenshot from 2017-12-05 15-34-23
screenshot from 2017-12-05 15-34-35
screenshot from 2017-12-05 15-34-43

### Pull Request Checklist

(Please keep this section. It will make maintainer's life easier.)

1. [x] Privileged views and APIs are guarded by proper permission checks.
1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Database queries are optimized and the number of queries is constant.
1. [x] The changes are tested.
1. [x] The code is documented (docstrings, project documentation).
1. [x] Python code quality checks pass: `pycodestyle`, `pydocstyle`, `pylint`.
1. [x] JavaScript code quality checks pass: `eslint`.

### CODE REVIEW

**Comment by patrys** [comment]
Long descriptions causing the table to expand make it hard to click "edit" on the correct row.

**Comment by koradon** [comment]
@patrys yes the JS need to be changed. Right now there is data-action-go on whole table row. This need to be changed.

**Comment by koradon** [comment]
@patrys if you mean Edit/Remove buttons on the first category list, they are removed. Also in commit 5b0c5fd i added truncatewords for description in this view. So screenshots from the PR comment are not up to date.

**Comment by dominik-zeglen** [comment]
Viva la .ignore-link class!

**Comment by koradon** [comment]
Updated screenshots added to PR comment.

**Comment by elwoodxblues** [comment]
Looks good. Is the "description" column aligned to the right on the first screen?

**Comment by koradon** [comment]
@elwoodxblues yes it looks like it. I had quite many conflicts on this file so maybe i missed sth. I will take a look on master.

**Comment by elwoodxblues** [comment]
Only prices are aligned to the right, the description column should be left-aligned as all other text columns.

**Comment by koradon** [comment]
@elwoodxblues then we have problem on master :) just checked

**Comment by elwoodxblues** [comment]
When trying to add a new subcategory, this error in breadcrumbs occurs: 
image

**Comment by patrys** [comment]
How does one tell whether a category is "hidden"? While we're at it we should probably rename "hidden" to something like "hide in site navigation".

**Comment by koradon** [comment]
@patrys @elwoodxblues how about a toggle similar to "Publish" from product details?

**Comment by koradon** [comment]
Updated screenshots added to PR comment.

**Comment by patrys** [comment]
I don't think we need a toggle. The toggle is there for products because every product will eventually become published. This is not true for categories, some categories are meant to appear in the top navigation and some are not. I think the "hidden" flag does not hide them anywhere else.

**Comment by koradon** [comment]
@patrys i just added a new screenshots. With @elwoodxblues, we decided not to add 'toggle' for is_hidden flag.

**Comment by elwoodxblues** [comment]
@koradon Few changes that come to my mind after reviewing the screenshots:
- "Hidden" column would look better as the third one, after the description.
- In the delete confirmation modal, I would put the subcategories in one line and separate them with commas.

**Comment by patrys** [comment]
Again, I don't think "hidden" is either self-explanatory or accurate as a name. It's essentially a "double-negative" example, as disabling it means the category is not *not* displayed in top navigation.

**Comment by elwoodxblues** [comment]
@patrys What column header and values do you suggest then?

**Comment by koradon** [comment]
Maybe we should rename it to 'is_featured'?

**Comment by koradon** [comment]
Updated screenshots added to PR comment.

**Comment by patrys** [comment]
@elwoodxblues I don't think it's super needed in the table list of categories, maybe as an icon. As @koradon suggested, we should rename this field to its counterpart, something like "is_visible_in_navigation" and give it a similarly descriptive label when presented as a checkbox.

**Comment by koradon** [comment]
@patrys @elwoodxblues with this field name change (to "is_visible_in_navigation") we need to rewrite all logic for 'is_hidden' field. From negative to positive. Make custom migration and so on. Maybe we should do this in separate PR?

**Comment by elwoodxblues** [comment]
To avoid that we could change it to `is_hidden_in_navigation`, just to make it more explicit, but I agree, that it starts to sound as a separate PR, as this change would touch modules unrelated to original changes from this PR.

**Comment by patrys** [comment]
Let's go separate and just drop this field from table list for now.

@elwoodxblues I think negative flags (is_deleted, is_hidden) to be way more error-prone when exposed in UI.

**Comment by koradon** [comment]
@elwoodxblues ok new screenshots added to PR comment

**Pull request merged**
