### PR TITLE
Convert payloads from generator to list

### PR DESCRIPTION
**Pull request by artopolisco**
Solves the error of kombu.exceptions.EncodeError: Object of type 'generator' is not JSON serializable

I want to merge this change because of kombu serialization error when Google Analytics is enabled:
[36mweb            |[0m kombu.exceptions.EncodeError: Object of type 'generator' is not JSON serializable
[36mweb            |[0m UWSGI uwsgi "POST /dashboard/products/6/variants/add/ HTTP/1.1" 302 325 28ms [PID:137:Worker-1] [RSS:125MB]
[36mweb            |[0m ERROR saleor.core.middleware Unable to update analytics [PID:128:uWSGIWorker2Core0]
[36mweb            |[0m Traceback (most recent call last):
[36mweb            |[0m   File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
[36mweb            |[0m     yield
[36mweb            |[0m   File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
[36mweb            |[0m     payload = encoder(data)
[36mweb            |[0m   File "/usr/local/lib/python3.6/site-packages/kombu/utils/json.py", line 69, in dumps
[36mweb            |[0m     **dict(default_kwargs, **kwargs))
[36mweb            |[0m   File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
[36mweb            |[0m     **kw).encode(obj)
[36mweb            |[0m   File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
[36mweb            |[0m     chunks = self.iterencode(o, _one_shot=True)
[36mweb            |[0m   File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
[36mweb            |[0m     return _iterencode(o, 0)
[36mweb            |[0m   File "/usr/local/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
[36mweb            |[0m     return super(JSONEncoder, self).default(o)
[36mweb            |[0m   File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
[36mweb            |[0m     o.__class__.__name__)
[36mweb            |[0m TypeError: Object of type 'generator' is not JSON serializable

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] Database migration files are up to date.
1. [x] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] GraphQL schema and type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by maarcingebala** [comment]
Thanks for opening this PR! As far as I remember this issue hasn't been reported, how can we reproduce it?

**Comment by artopolisco** [comment]
T

> Thanks for opening this PR! As far as I remember this issue hasn't been reported, how can we reproduce it?

To reproduce it, enable google analytics by setting the GOOGLE_ANALYTICS_TRACKING_ID environment, and then start the django app.

**Comment by maarcingebala** [comment]
I wasn't able to reproduce that. I'm closing this PR, but we can get back to it if anybody can confirm that the issue exists.

**Comment by hairychris** [comment]
I'm seeing this issue

```
web_1                       | ERROR saleor.core.middleware Unable to update analytics [PID:16:uWSGIWorker3Core0]
web_1                       | Traceback (most recent call last):
web_1                       |   File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 50, in _reraise_errors
web_1                       |     yield
web_1                       |   File "/usr/local/lib/python3.6/site-packages/kombu/serialization.py", line 221, in dumps
web_1                       |     payload = encoder(data)
web_1                       |   File "/usr/local/lib/python3.6/site-packages/kombu/utils/json.py", line 69, in dumps
web_1                       |     **dict(default_kwargs, **kwargs))
web_1                       |   File "/usr/local/lib/python3.6/json/__init__.py", line 238, in dumps
web_1                       |     **kw).encode(obj)
web_1                       |   File "/usr/local/lib/python3.6/json/encoder.py", line 199, in encode
web_1                       |     chunks = self.iterencode(o, _one_shot=True)
web_1                       |   File "/usr/local/lib/python3.6/json/encoder.py", line 257, in iterencode
web_1                       |     return _iterencode(o, 0)
web_1                       |   File "/usr/local/lib/python3.6/site-packages/kombu/utils/json.py", line 59, in default
web_1                       |     return super(JSONEncoder, self).default(o)
web_1                       |   File "/usr/local/lib/python3.6/json/encoder.py", line 180, in default
web_1                       |     o.__class__.__name__)
web_1                       | TypeError: Object of type 'generator' is not JSON serializable
```

**Comment by hamma2** [comment]
I have the same issue to after I deployed to beanstalk.
```
/var/log/eb-docker/containers/eb-current-app/eb-d5c249ad18da-stdouterr.log
-------------------------------------
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type generator is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./saleor/core/middleware.py", line 27, in middleware
    client_id, path=path, language=language, headers=headers)
  File "./saleor/core/analytics.py", line 68, in report_view
    _report(client_id, payloads, extra_headers=extra_headers)
  File "./saleor/core/analytics.py", line 36, in _report
    **extra_data)
  File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line 427, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line 544, in apply_async
    body, serializer,
  File "/usr/local/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type generator is not JSON serializable
ERROR saleor.core.middleware Unable to update analytics [PID:17:uWSGIWorker2Core0]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type generator is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./saleor/core/middleware.py", line 27, in middleware
    client_id, path=path, language=language, headers=headers)
  File "./saleor/core/analytics.py", line 68, in report_view
    _report(client_id, payloads, extra_headers=extra_headers)
  File "./saleor/core/analytics.py", line 36, in _report
    **extra_data)
  File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line 427, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/lib/python3.7/site-packages/celery/app/task.py", line 544, in apply_async
    body, serializer,
  File "/usr/local/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/kombu/serialization.py", line 54, in _reraise_errors
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "/usr/local/lib/python3.7/site-packages/vine/five.py", line 194, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/kombu/serialization.py", line 50, in _reraise_errors
    yield
  File "/usr/local/lib/python3.7/site-packages/kombu/serialization.py", line 221, in dumps
    payload = encoder(data)
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/json.py", line 69, in dumps
    **dict(default_kwargs, **kwargs))
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.7/site-packages/kombu/utils/json.py", line 59, in default
    return super(JSONEncoder, self).default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type generator is not JSON serializable
UWSGI uwsgi "GET /de/cart/summary/ HTTP/1.1" 200 785 29ms [PID:17:Worker-2] [RSS:162MB]```

**Comment by hairychris** [comment]
@maarcingebala I still need this patch, 3 of us have the issue now, this warrants further investigation.

**Comment by NyanKiyoshi** [comment]
I would recommend to open an issue with the steps to reproduce this so it can be investigated and properly tested.

**Comment by RomanMelnyk113** [comment]
Still reproduces for me as well. No specific steps to reproduce, simply enabled google_analytics (as it says here - https://saleor.readthedocs.io/en/latest/integrations/googleanalytics.html) middleware and open any page and boom, error described above appear upon sending task to celery.

**Comment by jtomaszon** [comment]
Same issue here!

**Comment by kevin-eom** [comment]
Is this caused by version or setting?
I'm seeing same error. I'm using python 3.6.7 version.
@maarcingebala @artopolisco

**Comment by blockchainunchained** [comment]
No idea, mirumee are convinced this bug isn't real despite the number of us reporting it here. Deploy a fresh instance onto a Digital Ocean Ubuntu Droplet and you will encounter this error. Still, I guess we must be imagining it.

**Comment by JannikZed** [comment]
We are facing the same issue - I was hoping to see eCommerce results in google analytics soon

**Pull request closed without merging**
