### PR TITLE
Add support to Google Cloud Storage

### PR DESCRIPTION
**Pull request by chetabahana**
Update and resubmit [file changes](https://github.com/mirumee/saleor/pull/2626/files) to add support to [Google Cloud Storage](https://cloud.google.com/storage/) through [django-storages[google]](https://django-storages.readthedocs.io/en/latest/backends/gcloud.html).

### Reference 
[PR#2626 ](https://github.com/mirumee/saleor/pull/2626)

### Basic Code
```
$ pipenv install django-storages[google]
$ pipenv lock -r > requirements.txt
$ pipenv lock -r -d > requirements_dev.txt
```

### Modified Files
- Pipfile
- Pipfile.lock
- requirements.txt
- requirements_dev.txt
- saleor/settings.py
- saleor/core/storages.py
- docs/deployment.rst
- docs/deployment/gcs.rst

### Link to Build Logs
- [Docker Hub](https://cloud.docker.com/repository/registry-1.docker.io/chetabahana/saleor/builds/b241c626-4ba9-4556-9a8c-e98c50eec1bc)

### Pull Request Checklist

1. [x] Privileged views and APIs are guarded by proper permission checks.
1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Database queries are optimized and the number of queries is constant.
1. [ ] Database migration files are up to date.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).
1. [ ] GraphQL schema and type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by maarcingebala** [comment]
Thanks for opening this PR @chetabahana. Since we have a [section about using S3 in our docs](http://docs.getsaleor.com/en/latest/deployment/s3.html), we should add a similar page for Google Cloud Storage. Do you think you could handle it?

**Comment by chetabahana** [comment]
> Thanks for opening this PR @chetabahana. Since we have a [section about using S3 in our docs](http://docs.getsaleor.com/en/latest/deployment/s3.html), we should add a similar page for Google Cloud Storage. Do you think you could handle it?

@maarcingebala 
Thank you for your respond. Yes, I am prepared to manage a documented page for Google Cloud Storage similar to [the section for S3](http://docs.getsaleor.com/en/latest/deployment/s3.html).

**Comment by maarcingebala** [comment]
@chetabahana Great! You can follow a similar structure as for that S3 page that I've linked. Let me know if you need any help or anything is unclear.

**Comment by chetabahana** [comment]
> @chetabahana Great! You can follow a similar structure as for that S3 page that I've linked. Let me know if you need any help or anything is unclear.

@maarcingebala Done! I have included following files in this PR to add docs page for Google Cloud Storage with similar structure as for that S3 page:
- docs/deployment.rst (modified)
- docs/deployment/gcs.rst (added)

**Comment by maarcingebala** [comment]
Thanks @chetabahana and congrats on your first PR to Saleor! Also thanks to @sergioisidoro for initial work on this.

**Pull request merged**
