### PR TITLE
Fallback for SKU if VariantName and attributes are missing

### LINKED ISSUE #1846: Product variant without name or attrs displays as blank space in dashboard's breadcrumbs
Seems like `__str__` on our `ProductVariant` may produce empty string if ProductVariant has no name or attributes set. Our titles seem to fallback to SKU if this is the case, but not our breadcrumbs:

zrzut ekranu 2018-03-01 o 13 58 23

### PR DESCRIPTION
**Pull request by Pacu2**
Variant's `__str__` fallsback for sku if its name or display_attributes are missing.
close #1846 

### Pull Request Checklist

(Please keep this section. It will make maintainer's life easier.)

1. [x] Privileged views and APIs are guarded by proper permission checks.
1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Database queries are optimized and the number of queries is constant.
1. [x] The changes are tested.
1. [x] The code is documented (docstrings, project documentation).
1. [x] Python code quality checks pass: `pycodestyle`, `pydocstyle`, `pylint`.
1. [x] JavaScript code quality checks pass: `eslint`.

### CODE REVIEW

**Comment by mad-anne** [comment]
It was intended to be empty. We use `display_product()` method from variant to get product representation saved to `OrderLine` and it returns product name if variant's representation is empty. It prevents displaying duplicated `SKU` in order details view. But maybe we should find better solution to correctly display variants in many different places.

**Comment by elwoodxblues** [comment]
Recently we've been talking about dropping the variant name field as it doesn't seem to be very useful. A variant representation should be constructed of its attributes. Although our model allows it, I think having a variant without attributes doesn't make sense. I wouldn't change this behavior for now, but I think SKU is good fallback here.

**Comment by elwoodxblues** [comment]
@Pacu2 Is this PR still valid or does #2026 fix this by any chance?

**Comment by Pacu2** [comment]
@elwoodxblues this solves the problem until we make at least 1 attribute required per variant

**Comment by elwoodxblues** [comment]
@Pacu2 Could you fix the tests here?

**Pull request merged**
