### PR TITLE
Test if the product attributes view is correctly handled when no results

### LINKED ISSUE #3027: Test no result view on attributes
We should add a test, to check if no result dashboard view on attributes is handled properly.
Related:
#3024 
#3026

### PR DESCRIPTION
**Pull request by NyanKiyoshi**
Close #3027.
Merges to #3026.

### Pull Request Checklist

1. [x] Privileged views and APIs are guarded by proper permission checks.
1. [x] All visible strings are translated with proper context.
1. [x] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Database queries are optimized and the number of queries is constant.
1. [x] The changes are tested.
1. [x] The code is documented (docstrings, project documentation).
1. [x] GraphQL schema and type definitions are up to date.

### CODE REVIEW

**Comment by maarcingebala** [comment]
Hey @NyanKiyoshi, could you rebase this branch with the latest master? There was a bug in tests which causes tests in this PR to fail.

**Comment by NyanKiyoshi** [comment]
@maarcingebala I got that, but the issue is that I want to merge this PR to `mirumee:3024/incorrect-product-attribute-template-name`. So I don't know if you want to merge it that way and it won't mess the history? Or @Pacu2 (or someone else) rebases `mirumee:3024/incorrect-product-attribute-template-name` to `master` to fix it?

**Comment by Pacu2** [comment]
Closed the other PR, let's just handle that in this one

**Comment by Pacu2** [comment]
Thanks for picking this up

**Pull request merged**
