### PR TITLE
Convert Saleor to TS

### LINKED ISSUE #862: Switch to Webpack 2
It's finally out of beta 🎊 !

### PR DESCRIPTION
**Pull request by patrys**
Fixes #862 

TODO:
* [ ] extract-text-webpack-plugin is still in RC

### CODE REVIEW

**Comment by patrys** [comment]
Let's discuss!

**Comment by mirekm** [comment]
I'm not sure amount of code should be an argument here. The biggest gains of having TS would be of course around refactoring and simplified code review process thanks to types inference. I would be against having the strict types policy for now tho at the same time.

**Comment by patrys** [comment]
To counter that argument TypeScript has nothing to do with being single-page and it would help us avoid many problems. We're going to have more and more front-end code as more views are planned to convert to React (checkout is next). Having worked with properly-annotated third-party code I see great value in static checks. They are helpful when writing code but where they really shine is working with code written by someone else. Eslint will not be able to help us here and I find TypeScript much cleaner than Flow. Flow shares the same entry level problem.

**Comment by patrys** [comment]
As for the difficulty I also thing that being able to point people to single document for TypeScript is immensely better than having to list all of the babel plugins we use (effectively making the language we use a Mirumee-favored JavaScript).

**Comment by elwoodxblues** [comment]
I agree with pros mentioned by @patrys. However I'm still not 100% convinced that switching to TS is a good idea. Getting used to TypeScript and it's ecosystem takes some time, even if we'd provide all the configuration and tools along with Saleor. I'm thinking about people who don't have experience with TS but want to change something in frontend code. They may encounter difficulties with some aspects of TS that are not present in JS like types, interfaces, problems with libraries without types etc. As for Babel - you don't have to necessarily understand how each plugin works to get it running and be able to do some changes.

**Comment by patrys** [comment]
One of the problems I'm trying to solve is having better QA for front-end code. I only see two paths here: Flow and TypeScript.

**Comment by elwoodxblues** [comment]
That's why I would choose TS in a typical single page app. If we decided on rewriting most of our views to JS then I'd consider TS, now we have barely one view plus one component in another one.

**Comment by patrys** [comment]
Ok so the downside we see is potentially having to deal with types? With implicit "any" types should only become visible once you make an error calling a strictly typed function though.

Food for thought: GraphQL is way more advanced than TypeScript, do we think it will hinder adoption?

**Pull request closed without merging**
