### PR TITLE
Implement payrexx as payment provider

### PR DESCRIPTION
**Pull request by sacovo**
I implemented a payment gateway that allows to add payrexx as an payment provider. Payrexx offers a lot of different payment options besides credit cards, like bank transactions or mobile payment methods as for example Twint in Switzerland.

The implementation mostly follows the stripe integration, with a few modifications.
### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] Database migration files are up to date.
1. [ ] The changes are tested.
1. [ ] GraphQL schema and type definitions are up to date.
1. [ ] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by django-queries** [comment]
Here is the report for 97221ec52d081954a897e00ecf2a8df07e05d8a8 (sacovo/saleor @ payrexx)
Base comparison is 26cc2d72b5a4192bd79e4792d76e943ea61e4fec.



<details><summary>No differences were found. (click me)</summary>
<p>

```diff
# api.benchmark checkout
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  add billing address to checkout     	         34	         34	             20
  add shipping to checkout            	          7	          7	              0
  checkout payment charge             	         14	         14	              0
  complete checkout                   	          6	          6	              0
  create checkout                     	         48	         48	             24

# api.benchmark homepage
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  retrieve main menu                  	          5	          5	              0
  retrieve product list               	          4	          4	              0
  retrieve secondary menu             	          5	          5	              0
  retrieve shop                       	          2	          2	              0

# api.benchmark product
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  product details                     	         13	         13	              3

# api.benchmark variant
  test name                           	left count 	right count	duplicate count
  ------------------------------------	-----------	-----------	---------------
  retrieve variant list               	         15	         15	              8
```

</p>
</details>

**Comment by maarcingebala** [comment]
Hey, thanks for opening the PR! It'll be great to have another payment gateway supported in Saleor. We're now refactoring the underlying payments architecture so that each gateway is a plugin that can be turned on/off through API. Once the plugin architecture is ready, we want to move the payment gateways to separate repositories (which I hope would happen within the next few months).
I suggest holding on with this PR and getting back to it once we sort out the new architecture.

**Comment by salwator** [comment]
Hi @sacovo 
Thank you for contributing your work and integrating new payment provider with saleor!
We recently changed our payment architecture to entirely base on new _plugins_. We would like to encourage community to implement new extensions to saleor as separate packages and share with other as separate repositories/packages. It would be difficult for us to maintain all integrations as part of core saleor, that's why we would like them to be maintained externally.

To add new payment plugin, you could easily add git submodule to relevant place in payment.gateways, just use absolute imports for payment interfaces and do not import anything else. In near future we will continue our work on plugin system so it provides additional package for interfaces and handles external paths during plugin discovery. After this work is done, you will be able to use standalone package with saleor plugin without any modification in saleor itself.

Please let me know if you have any questions.

**Comment by sacovo** [comment]
Thanks for your feedback. In this case I will wait until you ready with the new api and create a separate package.

**Comment by maarcingebala** [comment]
I'm closing this PR then. We'll get back to it once we improve our architecture to allow for plugins from external repositories.

**Pull request closed without merging**
