### PR TITLE
Fix category image url

### PR DESCRIPTION
**Pull request by benekex2**

### CODE REVIEW

**Comment by artursmet** [comment]
It works when assets on S3, SVG images are inlined.

**Comment by patrys** [comment]
That's not what I meant when I said "inlined". We want the SVG to become part of the DOM, not to encode it as part of `url(data:...)`.

**Comment by elwoodxblues** [comment]
@patrys Could you take a look at this one? SVG images are inlined now.

**Comment by patrys** [comment]
Do we have any non-React components that use SVG?

**Pull request merged**
