### PR TITLE
Add model translations

### PR DESCRIPTION
**Pull request by fpytloun**
This change adds model translations using django-modeltranslation project

#815

It seems to be much simpler solution than #819

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [ ] Database queries are optimized and the number of queries is constant.
1. [ ] The changes are tested.
1. [ ] The code is documented (docstrings, project documentation).

### CODE REVIEW

**Comment by patrys** [comment]
I'm not a fan of `django-modeltranslation` and other solutions that involve meta-programming and magic. That's why we came up with a direct implementation in #819.

**Comment by fpytloun** [comment]
I tend to agree with avoiding meta-programming and magic.
But #819 is 1,5 year old change with +325 −23 lines of code and there's obviously no one willing to finish it.
Vs. this super simple solution with +84 −10 lines of code by re-using existing framework for model translations.. and it just works out of the box (I was pretty surprised how easy it was to use it).

**Comment by patrys** [comment]
To provide some context: #819 is our internal work and we are willing to finish it and get it merged but we consider finishing the new dashboard to be of higher priority.

**Comment by NyanKiyoshi** [comment]
On a side note (still meta-programming), there is `django-hvad` that is cleaner and seems to work quite nicely. But no django 2.0 support.

**Comment by maarcingebala** [comment]
We've started a new PR (#2475) that implements model translations. We want to use our solution as it will be easier and more versatile to implement in GraphQL API, instead of dynamically generated fields in `django-modeltranslation`. @fpytloun I'm closing this PR, but want to thank you for your efforts anyway, we appreciate that 🙂.

**Pull request closed without merging**
