### PR TITLE
[WIP] Feature/updates docker

### PR DESCRIPTION
**Pull request by rosscdh**
A few missing steps in the dockerfile. 

1. install npm
2. add steps to migrate intsall n and n v6.11.1
3. yarn
4. yarn run build-assets

atm also looks like svg2png dependency is not pinned is causing build errors with yarn build-assets

### CODE REVIEW

**Comment by rosscdh** [comment]
ModuleBuildError: Module build failed: Error: Command failed: /app/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs /app/node_modules/favicons/node_modules/svg2png/lib/converter.js {"height":920,"width":640}

**Comment by rosscdh** [comment]
removed my refs to django in the dockerfile.. only used to prepare image not execute anything on the box

RUN django-admin.py compilemessages
RUN python /app/manage.py migrate

**Comment by patrys** [comment]
I'm not sure we want the docker image to contain npm, node and node_modules. By the time you package the container all of the assets should be compiled and docker should only have to collect the resulting artifacts. If you want to avoid having to deal with node on your dev machine, you can use a separate docker-compose service to handle that.

**Comment by rosscdh** [comment]
This is an interesting topic!

Am of the same opinion, but the sell to developers is not one for just
packaging but for the whole env to be encapsulated.

Am working on a similar idea with a docker container builder folder and a
root dockerfile and compose. The trick is that for dev needs to mount the
local source dir instead of using copy or add.

Usually takes form of

1. Make build-assets - uses dockerfile with mom etc to build assets
2. Make run-develop - starts with local src mounted at entrypoint
2. Make build-container - to build container with assets
3. Make publish-container - does what it says on label

Am interested in contributing if makes sense?

**Comment by patrys** [comment]
Yes, my main concern is that the main docker image should not contain 600+ MB of `node_modules`. That's why in cases like yours we usually use two machines, one to run Python and one to run `yarn watch`. In local development both mount the working directory in its entirety using `docker-compose` but the underlying main image does not contain anything related to Node.

**Comment by rosscdh** [comment]
ok ill close, seems we are daccord. However the docs should probably be updated to be a bit more clear about that? ill make apr?

**Pull request closed without merging**
