### PR TITLE
Hungarian translations

### PR DESCRIPTION
**Pull request by hmikihth**
We want to merge our Hungarian translations.

### CODE REVIEW

**Comment by maarcingebala** [comment]
Thanks for opening this PR! We use [Transifex](https://www.transifex.com/mirumee/saleor-1/) for managing translations. Could you add the translations there instead?

**Comment by maarcingebala** [comment]
I'm closing this PR, @hmikihth let me know if you have any problems with uploading translations to Transifex.

**Comment by hmikihth** [comment]
Hi,

Sorry, our team prefer to use Github instead of Transifex. We don't like the Transifex because that is a little bit chaotic and slow.

**Comment by patrys** [comment]
We are unable to accept translations using GitHub because they would get overwritten every time we synchronize with Transifex. You can use the Transifex command line client to upload your translation files: `tx push -l hu` (assuming you first join the Hungarian translation team and authorize your client first).

**Pull request closed without merging**
