### PR TITLE
Improvements on shipping validation

### PR DESCRIPTION
**Pull request by jxltom**
- Reuse ```is_valid_shipping_method``` in API (```clean_checkout```) and storefront 1.0 (```clean_shipping_method```)
- Split ```clean_shipping_method``` to ```clean_shipping_method``` and ```clean_shipping_address```. They are used in ```CheckoutLinesAdd```/```CheckoutLineUpdate```/```CheckoutLineDelete```/```CheckoutShippingAddressUpdate```/```CheckoutShippingMethodUpdate```. I feels both address and method should be validated after cart line/shipping method/shipping address are updated.
- Fix a bug where address and method should be validated **after** cart line is updated in ```CheckoutLinesAdd```/```CheckoutLineUpdate```
- Fix a bug where checkout is not returned if method/address is invalid in ```CheckoutLinesAdd```/```CheckoutLineUpdate```
- Fix a bug where shipping method should be deleted only when it's invalid in ```clean_shipping_method```
- Fix a bug where ```is_valid_shipping_method``` will raise error if cart doesn't have a shipping address
- Fix bug where ```Country``` should be used instead of string for address's country field in tests.

### Pull Request Checklist

1. [ ] Privileged views and APIs are guarded by proper permission checks.
1. [ ] All visible strings are translated with proper context.
1. [ ] All data-formatting is locale-aware (dates, numbers, and so on).
1. [x] Database queries are optimized and the number of queries is constant.
1. [x] Database migration files are up to date.
1. [x] The changes are tested.
1. [x] The code is documented (docstrings, project documentation).
1. [x] GraphQL schema and type definitions are up to date.
1. [x] Changes are mentioned in the changelog.

### CODE REVIEW

**Comment by auvipy** [comment]
could you rebase and make build pass? good progress so far!

**Comment by jxltom** [comment]
@auvipy Is this a auto reply? :smile:

**Comment by jxltom** [comment]
@maarcingebala This PR is updated with master branch, please review. Thanks.

**Comment by maarcingebala** [comment]
Closing in favor of #4367 where we're working on improved behavior of checkout API.

**Pull request closed without merging**
