### PR TITLE
Fix performance of product type and attributes fields

### PR DESCRIPTION
**Pull request by maarcingebala**
Adds data loaders for:
- `Product.productType`
- `ProductType.productAttributes`
- `ProductType.variantAttributes`

# Impact

* [ ] New migrations
* [ ] New/Updated API fields or mutations
* [ ] Deprecated API fields or mutations
* [ ] Removed API types, fields, or mutations
* [ ] Documentation needs to be updated

# Pull Request Checklist

* [ ] Privileged queries and mutations are guarded by proper permission checks
* [ ] Database queries are optimized and the number of queries is constant
* [ ] Database migration files are up to date
* [ ] The changes are tested
* [ ] GraphQL schema and type definitions are up to date
* [ ] Changes are mentioned in the changelog

### CODE REVIEW

**Comment by patrys** [comment]
Task linked: [SALEOR-1195 Slow performance when filtering products by attributes](https://app.clickup.com/t/2549495/SALEOR-1195)

**Comment by patrys** [comment]
@maarcingebala Any idea why the query checker shows no differences?

**Comment by maarcingebala** [comment]
No benchmark, I presume.

**Comment by maarcingebala** [comment]
Adding one now.

**Review by patrys — APPROVED** [review]

**Review by IKarbowiak — APPROVED** [review]

**Pull request merged**
